### ISSUE TITLE
Use without unlock 

### ISSUE THREAD

**Issue by github2099** [raivo-otp/ios-application#101]
can I use the app without setting password/faceid/touchid?

**Comment by tijme** [comment]
Due to security reasons this is not possible. The encryption in use is all based on a master password + passcode entered by the user. Due to the same security reasons I'm not planning on removing the lockscreen of the app. Sorry.

**Comment by github2099** [comment]
What if user can set a custom inactivity lock.? Say one can set it to be 24 hours, and keep that in background. That's basically bypass the passcode but still have the encryption. Just my thoughts

**Comment by tijme** [comment]
This is genius. Maybe I'll implement this, for 24 hours, or even more. Thanks for the input.
