### ISSUE TITLE
Personal Cloud Issue

### ISSUE THREAD

**Issue by sabregames27** [raivo-otp/ios-application#104]
**Describe the bug**
Unable to sync to personal cloud, just local device

**To Reproduce**
Install app and set it up, greeted out option

**Expected behavior**
Sync to icloud

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 14.3
 - Version Latest at time

**Additional context**

**Comment by tijme** [comment]
Closing this as it's being tracked in #64
