### ISSUE TITLE
It would be nice to have a static website for raivo.

### ISSUE THREAD

**Issue by therealmrmuffin** [raivo-otp/ios-application#106]
**Is your feature request related to a problem? Please describe.**
No it's not.

**Describe the solution you'd like**
I would like for Raivo to have it's own static site. What i mean by this is that, i would like for this project to start it's own website to where people can visit it to find and download Raivo. Rather than forcing people to use the GitHub repo.

**Additional context**
I would like for Raivo to have it's own static site. To make it easier for people to find, navigate, and download the application. The less technical people in the crowed won't probably even know what GitHub is and that's why i would recommend you look into this. You can host a website for free with GitHub pages and register a domain with namecheap.com or porkbun.com for example, to get a domain like "raivo.org", "raivo-otp.com", and or "theraivoproject.org".

**Comment by cjerrington** [comment]
I'd be happy to help create a website for this. I have a theme in mind and could easily get a prototype going for you. I can work on something over the next week or so.

**Comment by MrMuffinIsTaken** [comment]
@cjerrington you would have to ask @tijme seen as he's the maintainer of raivo.

**Comment by cjerrington** [comment]
@tijme let me know if this is something you're interested in. Can easily be another website repo and run the site from there or off netlift as well to serve it.

**Comment by tijme** [comment]
Hey people. This seems like a great idea and I'd love Raivo to have its own website. However, I feel like I cannot contribute to this at the moment.

* This is a project that I can only spend my free time on, and all my free time goes to the application itself.
* I cannot afford the domain as I do not make any money from Raivo. My Apple Developer license + push notification server already cost me money and I'd not like to increase these costs.
* I already have a support website running [at Freshdesk](https://raivo.freshdesk.com/support/home), the support site is a requirement from Apple.

It would be lovely if there was a website dedicated to the application on Github sites, with a Github subdomain. Feel free to contribute to it if you'd like! 🚀

**Comment by cjerrington** [comment]
I can get something started for you! I think the GitHub pages is a great idea - that is how I host a few of my sites as well. The domain if purchased now or later I could help with some of the costs too. This kind of open source app would do great with a website hosted on GitHub. Let me work something up for us, @tijme .

**Comment by therealmrmuffin** [comment]
I am willing to supply the costs for the domain (depending on the TLD, ccTLD, sTLD, gTLD, grTLD, and/or ARPA, price) and i am also willing to help manage the github pages repo as a issue and penitential PR reviewer. To talk about this further, you can reach me at the email address on my profile @tijme.

**Comment by tijme** [comment]
Really kind of you both! @cjerrington can't wait to see what you've created. I would propose te keep it simple and straightforward, so it needs as less maintenance as possible and it's easy to update, extend, etc.

What domain would you people propose? I'm thinking something with a `.com` domain as it's generally recognised as a valid TLD (unlike e.g. the more expensive `.app` TLD). Unfortunately `raivo.com` is taken and for sale for $250 (which is not an option of course). Maybe something like `raivo-app.com` or `raivo-otp.com`?

I will create a repository under the raivo-otp Github organisation so it can be forked and we can work on something. 🚀

**Comment by tijme** [comment]
Here's the repo: https://github.com/raivo-otp/marketing-website

**Comment by cjerrington** [comment]
Here is what I have as well simple Jekyll site on GitHub pages.

https://github.com/cjerrington/raivo-otp

https://claytonerrington.com/raivo-otp/

**Comment by therealmrmuffin** [comment]
> Really kind of you both! @cjerrington can't wait to see what you've created. I would propose te keep it simple and straightforward, so it needs as less maintenance as possible and it's easy to update, extend, etc.
> 
> What domain would you people propose? I'm thinking something with a `.com` domain as it's generally recognised as a valid TLD (unlike e.g. the more expensive `.app` TLD). Unfortunately `raivo.com` is taken and for sale for $250 (which is not an option of course). Maybe something like `raivo-app.com` or `raivo-otp.com`?
> 
> I will create a repository under the raivo-otp Github organisation so it can be forked and we can work on something. 🚀

I propose either a .net or .org, but mainly a .net seen as raivo is "code viewable" and not fully open source because of it not having a FOSS license.

**Comment by cjerrington** [comment]
I saw the pre-release notes and saw the springboard name will be changed to Raivo. So I think the Raivo.net would be a good choice. Let me know your thoughts on the initial website idea and I can then make a pull request for the marketing-site repo. One the domain is purchased I can help as well if needed linking the DNS to GitHub pages and properly link the two.

**Comment by elmedico27** [comment]
I highly recommend Cloudflare Pages.  Completely free and perfect use case for static sites.  You link to a GitHub repository and Cloudflare automatically publishes the changes in real-time, with all the benefits of their edge CDN, etc.  They also register domains at cost, so it’d be $10-12 USD per year (total!) for raivo.net and the site.

**Comment by therealmrmuffin** [comment]
> I saw the pre-release notes and saw the springboard name will be changed to Raivo. So I think the Raivo.net would be a good choice. Let me know your thoughts on the initial website idea and I can then make a pull request for the marketing-site repo. One the domain is purchased I can help as well if needed linking the DNS to GitHub pages and properly link the two.

Fair point, maybe we should do that. And in regards to DNS, i think @tijme can handle that him self seen as he's a pretty smart guy. Unless i need, witch can be done to, i am just not sure about the details yet.

**Comment by therealmrmuffin** [comment]
> I highly recommend Cloudflare Pages. Completely free and perfect use case for static sites. You link to a GitHub repository and Cloudflare automatically publishes the changes in real-time, with all the benefits of their edge CDN, etc. They also register domains at cost, so it’d be $10-12 USD per year (total!) for raivo.net and the site.

Seems a bit unnecessary from me, i use one registrar for everything. And also adding Cloudflare Pages is extra work on our end and is an unnecessary i think so.

**Comment by therealmrmuffin** [comment]
@cjerrington love your sample site btw, with just only the logos still and maybe some more red & a bit less JS, i think the site would look amazing.

**Comment by cjerrington** [comment]
I did notice there were a lot of extra calls to JS. I can't fix that and add some more of the red to it too!

**Comment by therealmrmuffin** [comment]
@cjerrington just to be clear, can't or can?

**Comment by cjerrington** [comment]
Auto-correct fail. I can fix it.

**Comment by therealmrmuffin** [comment]
Cool! Maybe do that and then we'll seen what @tijme thinks about it.

**Comment by therealmrmuffin** [comment]
@tijme i still don't know what to do. Do you want me to register a domain for you? Do you want me to make a payment via paypal to you?

**Comment by cjerrington** [comment]
There was a site.baseurl error. The site is based off JS and will pull a lot of content from the iTunes API for the icon, name, description, etc. We could also static this content, but depends on if we want to update the website as well, or have it pull the data from the source, iTunes. This is configured in the `_config.yml`. 

The Change log might be something we could pull from the main [GitHub repos API](https://api.github.com/repos/raivo-otp/ios-application/releases). This could be based on the latest release and build out a custom page with all the releases, last few or just the latest. I'd probably put this in the build of the site so its static content, but would require a trigger of the site to be built. If there is a `changelog.md` file in the main repo, we might be able to REST query the repo for the content of the file and make it on the site too. That would keep the change log in the main repo and the site is just a gatherer of information. Adding just a little more JS to a change log page wouldn't be that much more, and could be based on the `site.page` in Jekyll using templates to include the JS that is needed for that page specifically. 

If the rest of the site is static and pulls from the iTunes API so we dont have to update this site with content frequently, could a GitHub action be used to increase a release file here or rebuild this repo from the release process in the ios-application repo? 

A few thoughts on the few ways to accomplish @tijme request of the change log page.

**Comment by tijme** [comment]
> @tijme i still don't know what to do. Do you want me to register a domain for you? Do you want me to make a payment via paypal to you?

Sorry for the belated response. Was still thinking a bit about the domain. I eventually chose to register `raivo-otp.com`, as I think the `.net` & `.org` extensions do not really represent the purpose of Raivo. The `.com` TLD is more generally used (although it was for commercial purposes in the past). The `.app` TLD would have been the best, but it's too expensive.

I've registered `raivo-otp.com` via CloudFlare, which costs me $8.57 a year. It will be greatly appreciated if you donate via PayPal: https://www.paypal.com/paypalme/tijmegommers! 💸

**Comment by tijme** [comment]
> There was a site.baseurl error. The site is based off JS and will pull a lot of content from the iTunes API for the icon, name, description, etc. We could also static this content, but depends on if we want to update the website as well, or have it pull the data from the source, iTunes. This is configured in the `_config.yml`.
> 
> The Change log might be something we could pull from the main [GitHub repos API](https://api.github.com/repos/raivo-otp/ios-application/releases). This could be based on the latest release and build out a custom page with all the releases, last few or just the latest. I'd probably put this in the build of the site so its static content, but would require a trigger of the site to be built. If there is a `changelog.md` file in the main repo, we might be able to REST query the repo for the content of the file and make it on the site too. That would keep the change log in the main repo and the site is just a gatherer of information. Adding just a little more JS to a change log page wouldn't be that much more, and could be based on the `site.page` in Jekyll using templates to include the JS that is needed for that page specifically.
> 
> If the rest of the site is static and pulls from the iTunes API so we dont have to update this site with content frequently, could a GitHub action be used to increase a release file here or rebuild this repo from the release process in the ios-application repo?
> 
> A few thoughts on the few ways to accomplish @tijme request of the change log page.

I really like the idea of having a static website. It's what I have for my personal website (tij.me) as well. It does not use any JavaScript at all, which really speeds up loading times and improves security. It would be great if the website for Raivo could be JavaScript-less some day. However, I also see the problem of automatically retrieving the latest info (e.g. changelog) while the site is static.

Your idea on triggering an update of the repo when a new version of Raivo is released is great. I can build something that triggers a rebuild of the website when a new version of Raivo is released. In the beginning I can even do this manually. Does Jekyll support retrieving  e.g. the `body` value of this JSON content `https://api.github.com/repos/raivo-otp/ios-application/releases/latest`? If that can be parsed and build to a static changelog that would be great. We can even publish the entire changelog or a part of it using the GitHub API, like you said. That would be great.

What does the site exactly parse from the iTunes API? I don't see anything on the site that isn't in the GitHub repo already. 

It would be nice if we could somehow also parse the privacy/security policy from the iOS repo, and publish it as a static page in the website. We need something like a markdown to HTML parser in Jekyll. But I guess that's future work..

Regarding branding assets (logo's, screenshots, etc). You can find some of it in the iOS repo, as I see e.g. the main screenshot has two borders now.
* [Logo](https://github.com/raivo-otp/ios-application/tree/master/Assets)
* [Screenshots without frame](https://github.com/raivo-otp/ios-application/tree/master/Assets/simulator-screenshots)
* [Screencaptures without frame](https://github.com/raivo-otp/ios-application/tree/master/Assets/simulator-screencaptures)
* [Previews with frame](https://github.com/raivo-otp/ios-application/tree/master/Assets/appstore-previews)

It currently looks like this for me: 
![image](https://user-images.githubusercontent.com/5873573/180958952-9a7209b1-1ff2-427d-a654-480c92f60674.png)

**Comment by tijme** [comment]
Ah, I see that the missing logo is actually because of my AdBlocker.

**Comment by tijme** [comment]
@cjerrington just wanted to let you know I've updated the repo under the raivo-otp Github organisation with your code: https://github.com/raivo-otp/marketing-website. The website is published at `raivo-otp.com`. I've made a few changes, hope you don't mind about them:

* Textual changes in the title, description and features.
* Removed some of the configuration options (e.g. Instagram/Facebook URL etc).
* Changed the header background & color.
* Updated the logo to the latest version in Github.
* Updated the screenshot (the border is now removed).

If you want to you can fork it and continue working on this version/repo. I'll do my best to complete it further too. I'll see if I can work on the changelog * privacy policy part and such.

**Comment by cjerrington** [comment]
> @cjerrington just wanted to let you know I've updated the repo under the raivo-otp Github organisation with your code: https://github.com/raivo-otp/marketing-website. The website is published at `raivo-otp.com`. I've made a few changes, hope you don't mind about them:
> 
> * Textual changes in the title, description and features.
> * Removed some of the configuration options (e.g. Instagram/Facebook URL etc).
> * Changed the header background & color.
> * Updated the logo to the latest version in Github.
> * Updated the screenshot (the border is now removed).
> 
> If you want to you can fork it and continue working on this version/repo. I'll do my best to complete it further too. I'll see if I can work on the changelog * privacy policy part and such.

I like it! ultimately it's how you feel the site should represent the app as well. For the changelog I was thinking we could use the GitHub API to get the latest main release and then have a link to the GitHub repo to see the full change log information. I can make a pull request on the `marketing-site` moving forward. 

@tijme add the SSL redirects et. al on the settings page to always enforce SSL, after that I think we should be good. 

I would think this issue could be closed now that we have something off the ground we can work on. Thanks for everyone for the ideas and the ability to help get this started!

**Comment by tijme** [comment]
Just got the changelog working on my local dev machine. However, it seems like Github pages does not support Jekyll plugins, as it's executed with the `--safe` param 🤔  (https://stackoverflow.com/questions/53215356/jekyll-how-to-use-custom-plugins-with-github-pages). So I guess retrieving the JSON from the Github API won't work unless I build the site locally and then publish the static site to Github pages. Enough stuff to think about. I guess building it locally is not ideal, but retrieving it through JavaScript isn't either.

I'll keep this issue open until the site is in production and all app/assets link to it. *If you don't want to get spammed with e-mail notifications about this thread, please unfollow the thread*.

PS; i've enforced TLS connections in CloudFlare's configuration, including the use of HSTS.

**Comment by therealmrmuffin** [comment]
> Just got the changelog working on my local dev machine. However, it seems like Github pages does not support Jekyll plugins, as it's executed with the `--safe` param 🤔 (https://stackoverflow.com/questions/53215356/jekyll-how-to-use-custom-plugins-with-github-pages). So I guess retrieving the JSON from the Github API won't work unless I build the site locally and then publish the static site to Github pages. Enough stuff to think about. I guess building it locally is not ideal, but retrieving it through JavaScript isn't either.
> 
> I'll keep this issue open until the site is in production and all app/assets link to it. _If you don't want to get spammed with e-mail notifications about this thread, please unfollow the thread_.
> 
> PS; i've enforced TLS connections in CloudFlare's configuration, including the use of HSTS.

Okay. Not sure it will be possible. But it might be interesting see for sure.

**Comment by therealmrmuffin** [comment]
Opening a new issue at the new repo: https://github.com/raivo-otp/marketing-website/issues/1

**Comment by tijme** [comment]
Perfect, thanks @therealmrmuffin.

FYI; I got the automatic changelog, privacy policy and security policy working. I just have to click a single button on Github and it all regenerates and redeploys automagically 🔥 

Thanks for all the help and the donations. I'll take a look at the other marketing site related issues / pull request soon.
