### ISSUE TITLE
Apple Watch Companion App.

### ISSUE THREAD

**Issue by Ma-ikaJT** [raivo-otp/ios-application#108]
**Is your feature request related to a problem?**
No, it is not.

**Describe the solution you'd like**
I would like to see a counterpart to this app that is designed for Apple Watch.

**Describe alternatives you've considered**
I have yet to find a 2FA app that has both an Apple Watch and an iPhone app - in fact, the only ones I've found worth using so far are Twilio Authy and Microsoft Authenticator.

**Additional context**
I use Authy on my watch to quickly get access to 2FA codes without having to pull my phone out of my pocket.

**Comment by tijme** [comment]
Tracked in #17.
