### ISSUE TITLE
Make it harder to delete an entry.

### ISSUE THREAD

**Issue by ccouvillion** [raivo-otp/ios-application#109]
**Is your feature request related to a problem? Please describe.**
It seems rather simple to delete an entry. While I plan to make a local backup of the database, I worry that an errant swipe will clear an entry and cause me to have to recover an account.

**Describe the solution you'd like**
Move the delete option to the edit page so that it takes more effort to delete an entry.

**Describe alternatives you've considered**
In addition or alternative to moving the delete, add a 24 or 48 hour delay before the deletion completes. Authy does this, so you might check to make sure there would not be an issue if you implemented the feature.

**Additional context**

**Comment by tijme** [comment]
Are you aware of the confirmation popup after the tap on the delete button. So it's actually three interactions to delete a password.

1. Swipe on a password
2. Tap delete
3. Confirm to delete

**Comment by ccouvillion** [comment]
I am. I’m just paranoid. ;) 
While helpful when setting up my tokens, it seemed _to me_ a little overkill to have it so handy in daily use.

An undelete option of some sort would probably be a better option somewhere way down on the roadmap. It would not change current usage but would add an extra layer of recovery.

It was just a suggestion that came to my mind. I’ve taken a backup now that (almost) everything is out of Authy and will be happily using your lovely software. Thank you for creating a great app!

**Comment by tijme** [comment]
Someone requested a feature in #10 which is similar. Let's track it there!
