### ISSUE TITLE
Private Screen - iOS

### ISSUE THREAD

**Issue by brandonh3** [raivo-otp/ios-application#112]
**Is your feature request related to a problem? Please describe.**
When Raivo OTP shows up in the apps switcher on iOS, the app screen and 2FA codes remain visible. Would love to see the privacy screen feature (found in a lot of banking and financial apps, as well as other OTP apps) implemented for additional privacy. 

**Describe the solution you'd like**
This feature already exists in iOS and just needs to be implemented as an extra layer of privacy. 

**Describe alternatives you've considered**
This usually works by displaying an overlay with the app logo and hides all sensitive information.

**Additional context**
Tried to provide a screenshot, but I’m unable to paste it into this form.

**Comment by tijme** [comment]
Thanks for the request. Let's track this in #42.
