### ISSUE TITLE
Unlock using Biometrics doesn’t work on iPadOS with FaceID

### ISSUE THREAD

**Issue by mcx808** [raivo-otp/ios-application#115]
**Describe the bug**
I cannot use biometric unlock on iPadOS 15.3.1 on my iPad Pro with FaceID.
Every time it asks me to input the actual iPad device password to unlock.

It works fine on my iPhone with FaceID, and my other iPad with TouchID. Even toggling FaceID and setting a passcode for Raivo

**To Reproduce**
1. Go to 'settings'
2. Click on 'Face Id Unlock'
3. Exit Raivo
4. Re-Open Raivo, prompted for device password

**Expected behavior**
FaceID unlock is activate or at the very least the Raivo password prompt

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPad Pro 11]
 - OS: [e.g. iPadOS 15.3.1]
 - Version [1.3.3 b59]

**Additional context**

**Comment by tijme** [comment]
Is it really prompting for the device passcode? Or is it prompting for the Raivo passcode? Can you make a screenshot of the passcode input?

**Comment by mcx808** [comment]
Sorry, just reviewing my open issued. I thought I already replied with the screenshot. Here it is:
<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/30801293/164970869-f3624f84-c1ea-4fe4-83cd-1008bdd1c9e2.png">

**Comment by tijme** [comment]
@mcx808 Go to your Settings app on your iPad. Than scroll down to "Raivo". Enable "FaceID". Should work now.

**Comment by mcx808** [comment]
> @mcx808 Go to your Settings app on your iPad. Than scroll down to "Raivo". Enable "FaceID". Should work now.

Thanks, this worked for me. For anyone who stumbles on this thread, not sure how this could have been disabled except by backup / restore of the iPad. I certainly granted FaceID on the original prompt but mustn't have prompted again after restore and reloading the app.
