### ISSUE TITLE
Fido2 Support for SecurityKeys

### ISSUE THREAD

**Issue by svn2208** [raivo-otp/ios-application#116]
I would like to see fido2 support for my solokey  as alternative to faceid or touchid.

Do you see this in the near future?

**Comment by MrMuffinIsTaken** [comment]
@svn2208 this doesn't really make any senes to be honest with you. Why would you want to use a hardware 2FA key on you TOTP authenticator app? Your TOTP authenticator app already holds you TOTP seeds, so it not like you need to use a hardware token on the application. If you're really that dedicated, maybe use the TOTP authenticator of you hardware key (if it comes with one (witch most do)).-

**Comment by svn2208** [comment]
I am pretty new in the topic HW Keys, but my thought was: If the app supports FaceID/TouchID, why not a HW Key. 

I trust your opinion, and it makes somehow sense. 
You are free to close this issue.

**Comment by MrMuffinIsTaken** [comment]
@svn2208 that's alright. I was only saying it because to me didn't make too much senes. But if you really want them to add this, then i would say go for it. But if not, then you may close the issue, seen as i can't.
