### ISSUE TITLE
Passwords layout

### ISSUE THREAD

**Issue by caglaryalcin** [raivo-otp/ios-application#117]
I could not find the ability to change the location of passwords in the application.

I want them to be moved up or down when I hold down the passwords. This feature is available in authy.

Can you do this to make the app better?

**Comment by MrMuffinIsTaken** [comment]
@caglaryalcin we can't always have what we want. One way around this is to add them in order.

**Comment by caglaryalcin** [comment]
This is sad.. I didn't think it was anything difficult.

**Comment by MrMuffinIsTaken** [comment]
It sure is... But right now we can't do anything about it.

**Comment by cjerrington** [comment]
The accounts appear to be in alphabetical order for me regardless of the order the accounts are added. I can see how adjusting the sort order would be a nice add.

**Comment by cjerrington** [comment]
This seems related to issue #9 and issue #92

**Comment by tijme** [comment]
Tracking this in #9 indeed. Nice request! Seems to be doable. Just don't have the time to implement it at the moment.
