### ISSUE TITLE
Raivo app Serial Number or secret for manual code creation (unable to add Battle.net authenticator)

### ISSUE THREAD

**Issue by alexsaesee** [raivo-otp/ios-application#122]
**Is your feature request related to a problem? Please describe.**
I tried to add Raivo as the authenticator for battle.net website.  
Selected mobile authenticator : https://account.battle.net/security/authenticator/attach/mobile  
The website then ask for the _Serial number_ of the device wich I can't find on the Raivo app.

I tried to generate a Base32 key and use it as the Secret/Seed in a new entry in the Raivo app, then use it as the Serial Number but Battle.net say the serial number is invalid.

**Describe the solution you'd like**
In the Raivo app, show a Serial number in the settings or in a manual creation of a new entry.  
Linked (or not, I don't know), allowing the generation of a Secret/Seed for a new manual entry.

**Additional context**
Maybe I just didn't figured how to add the Raivo app as authenticator for Battle.net. If so, an explain of how to proceed will be appreciated.

Thanks!

**Comment by alexsaesee** [comment]
> To my knowledge you must use the Battle.net Authenticator App for Battle.net's 2FA. There have been requests that Blizzard allow users to use 3rd party TOTP authenticators but to date they have not replied to those requests.

Thank you for your answer. Will wait thme to allow it. No way I'll ue their authenticator, too bad memories with Square Enix and their own.

**Comment by khems** [comment]
https://www.reddit.com/r/Bitwarden/comments/iy4jh4/use_winauth_to_get_steam_and_battlenet_secrets/

You can export the secret from WinAuth and use it in Raivo (don't put the whole link in the field, just put the secret) and change the length to 8 digits. 

It'd be nice to have steam support too though

**Comment by alexsaesee** [comment]
This looks great (and I use Bitwarden too so win-win situation). Thanks for the input @khems .
