### ISSUE TITLE
Setup Password Change

### ISSUE THREAD

**Issue by Delogrand770** [raivo-otp/ios-application#123]
**Unable to change the encryption/setup key once established.**

_Describe the solution you'd like
A clear and concise description of what you want to happen._

**Add an option that provides the ability to change the encryption key if the original is provided correctly.**

_**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered._

**Reset Raivo, pick a new encryption/setup password and re-add all the OTPs.**

**Comment by alxgda** [comment]
Possible duplicate of https://github.com/raivo-otp/ios-application/issues/99

**Comment by tijme** [comment]
Duplicate of #41
