### ISSUE TITLE
I want to add the Fediverse icon to RaivoOTP but I have no clue where I should put it.

### ISSUE THREAD

**Issue by NylaTheWolf** [raivo-otp/ios-application#124]
**Is your feature request related to a problem? Please describe.**
I want to add the Fediverse icon to RaivoOTP but it's not a standalone website. It's a term used to describe social media apps that federate with one another, such as Mastodon, Pixelfed, PeerTube, Misskey, Friendica, etc.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
I don't know if I should just put it under Mastodon or maybe even Pixelfed. Or perhaps a workaround would be to put it under a folder titled `joinfediverse.wiki` (based on https://joinfediverse.wiki/Main_Page). Or should I forgo the website-based folder names entirely?

**Additional context**
N/A

**Comment by tijme** [comment]
For the folder name you can use the '.loc' extension if there is no website.
