### ISSUE TITLE
account type changed to offline even though i chose icloud

### ISSUE THREAD

**Issue by userat6** [raivo-otp/ios-application#129]
i have signed up with icloud sync and right before i reset my device, i saw the account was offline? now when i try login with offline and icloud, all my otp is gone. please help, i have used the right password and everything. i even restored from icloud backup of my apps and yet it doesnt show

**Comment by swimintospace** [comment]
I also had this same issue. Even after reinstalling the app, I can't chose to synchronize with my icloud backup. All my previous OTPs got wiped as well. When I check my iCloud, it still says that icloud is turned on for raivo OTP.

**Comment by swimintospace** [comment]
Go to your iCloud settings and make sure iCloud Drive is enabled. I also had this issue.

**Comment by tijme** [comment]
What @swimintospace says should help. ICloud drive should be enabled while syncing tokens (both when you store them, as well as when you restore them).
