### ISSUE TITLE
Unable to remove an entry

### ISSUE THREAD

**Issue by pedriceroburilero** [raivo-otp/ios-application#131]
Please include in the iOS app the option of removing an entry that is not longer in use by the user. Thank you!

**Comment by ramasatgithub** [comment]
> Please include in the iOS app the option of removing an entry that is not longer in use by the user. Thank you!
Swipe left and kindly notice rubbish bin.

**Comment by pedriceroburilero** [comment]
Didn't realise the app has a swipe action. It's all good now. ^5

**Comment by tijme** [comment]
👍
