### ISSUE TITLE
Keyboard vanishes when prompted to enter a pin during setup

### ISSUE THREAD

**Issue by NHungate** [raivo-otp/ios-application#135]
**Describe the bug**
When trying to do the initial setup, the keyboard vanishes and makes it impossible to proceed.

**To Reproduce**
1. Install the app for the first time
2. Proceed through the initial setup until you reach the prompt for a PIN
3. The keyboard will be rendered but invisible, making it impossible for most people to continue. The keyboard still exists and can be typed on, but the lack of a visual keyboard makes it tough to know if you’ve hit the right number.

**Expected behavior**
The numeric numpad should appear during the PIN entry screen

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.5
 - Version 1.4.0

**Comment by tijme** [comment]
Can you send me een screencapture @NHungate? I cannot replicate it. I'm on iOS 15.6.

**Comment by tijme** [comment]
Closing as inactive.
