### ISSUE TITLE
No filters added to make white icons visible in light mode, many icons are camouflaged.

### ISSUE THREAD

**Issue by NylaTheWolf** [raivo-otp/ios-application#136]
**Describe the bug**
When I use light mode on my iPhone, many icons aren't visible (or at least parts of the icons) or are hard to make out because they use white and thus blend in with the white background. In the [Issuer Icons repository](https://github.com/raivo-otp/issuer-icons#svg-requirements), the SVG Requirements sections mentions that it's okay if the icons are white or black because effects will be applied to make these icons visible in light or Dark Mode.

However, this doesn't seem to be the case in light mode (I haven't noticed any issues in dark mode. Icons that are white or have white sections without any outlines or backgrounds blend in with the white background for the app and it's hard or impossible to see them. The Issuer Icons repository's Read Me says that there should be effects on the icon to make it visible in Light or Dark Mode.

The icons look perfectly fine on dark mode though:

![](https://i.imgur.com/2lzsZXa.png)

**To Reproduce**
1. Have your system on light mode.
2. Go to one of your accounts (or scan a new one)
3. Go to the "Edit" page
4. Click on the icon and go to Raivo's icon repository
5. See camouflaged icons.

**Expected behavior**
Effects added to make the icons visible in light mode.

**Screenshots**
![](https://cdn.discordapp.com/attachments/881321063127076904/985990716964634634/IMG_9972.PNG)

![](https://cdn.discordapp.com/attachments/881321063127076904/985991272017829969/IMG_9979.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 15
 - Version 5

**Additional context**

**Comment by tijme** [comment]
Fixed in https://github.com/raivo-otp/ios-application/commit/098af66fb266e532305bc828cc0d4a2a5b0c80bb. Closing this issue as it will be pushed to public in a few weeks 🚀 . First has to go to some Apple verifications + beta testing.
