### ISSUE TITLE
QR codes can't be read when in dark mode

### ISSUE THREAD

**Issue by tasmo** [raivo-otp/ios-application#137]
**Describe the bug**
When providing QR codes to other apps while being in dark mode most apps cannot recognise the code as it is shown as white on black.

**To Reproduce**
1. Select the UI to be dark.
2. Swipe any entry and select QR code.
3. Try to scan it.
4. Can not be read.

**Expected behavior**
QR codes should not be inverted when joining the dark side.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 15
 - Version: 1.4.0

**Additional context**
Could effect issue https://github.com/raivo-otp/ios-application/issues/98 .

**Comment by divarre** [comment]
@tasmo What app do you use to scan the QR code on step 3?

I tested this:
1. Using an iPhone (iOS 15.5), switch to dark mode in Settings > Display & Brightness > Appearance > Dark
2. Swipe left on an entry and show the QR code
3. Using another device (iPad running iOS 15.5), open Raivo and tap `+` to scan a QR code
4. Scan the QR code from the first device
And that worked for me.

**Comment by tasmo** [comment]
> @tasmo What app do you use to scan the QR code on step 3? I was trying to replicate the issue, but it seems to be working for me.

I tested it the same way you did but on other devices and apps.
I tried to import it to 1password on macOS and to Android Aegis. Further I tried to get the code with https://github.com/zxing/zxing .

None of these method worked.

**Comment by winschdi** [comment]
I can confirm, the qr code in dark mode doesn't work with Android Aegis, it's not recognised as qr code.

**Comment by tijme** [comment]
This commit (https://github.com/raivo-otp/ios-application/commit/3a8ac0a07f887d3f32f90ded4675ff5bd8502aaa) probably fixes the issue. I tried scanning a QR-code using 1Password (as @tasmo stated didn't work) and after this commit it worked for me.

It will take a few weeks to get published to the AppStore.

**Comment by tijme** [comment]
Fixed in development. Closing this issue as it will be pushed to public soon (within a few weeks).
