### ISSUE TITLE
Export function generates empty zip file

### ISSUE THREAD

**Issue by avayl** [raivo-otp/ios-application#139]
**Describe the bug**
When exporting OTPs to Zip archive the generated file is always 22 bytes and empty. Tried opening with unarchiver on macos and tried sharing using different apps (telegram, airdrop, gmail)

**To Reproduce**
1. Try to export file

**Expected behavior**
Expect a file with my OTP backup

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 15.5

**Additional context**
Using the latest app from the app store.

**Comment by RivenNero** [comment]
Same here.

**Comment by ewollesen** [comment]
See also #138.

**Comment by Johan446** [comment]
Same here. Always 22 bytes

**Comment by tijme** [comment]
Duplicate of #134.
