### ISSUE TITLE
Need a Gaussian blur effect

### ISSUE THREAD

**Issue by AlanDinkle** [raivo-otp/ios-application#140]
**Is your feature request related to a problem? Please describe.**

When I switch this application out, it does not create a layer of protection to prevent others from getting the code.

**Describe the solution you'd like**

As stated above.

**Describe alternatives you've considered**

**Additional context**

**Comment by tijme** [comment]
Please adhere to the template to file the feature request. Requests not adhering to the template and not extensively describing the feature will be closed. With more info, we can reopen the feature request! 😄

**Comment by tijme** [comment]
I think this is similar to #42.
