### ISSUE TITLE
Unable to scan StubHub OTP QR code

### ISSUE THREAD

**Issue by JCKE** [raivo-otp/ios-application#141]
**Describe the bug**
When trying to scan the QR, Raivo reports Invalid QR Code. Instead, the code must be added manually.

**To Reproduce**
1. Go to stubhub.ca
2. Log in / make an account
3. Click on profile -> Settings -> Security Center
4. Enable 2FA and try scanning QR code

**Expected behavior**
Raivo will read QR code and add entry

**Screenshots**
![App-Screenshot](https://user-images.githubusercontent.com/6626801/177276578-b05a8643-10f3-4407-8290-b66db68e1003.PNG)
<img width="1724" alt="Stubhub-Screenshot" src="https://user-images.githubusercontent.com/6626801/177276599-2578309b-05d5-403f-adf8-d2757ea9f6eb.png">

**Smartphone:**
 - Device: iPhone SE 2020
 - OS: iOS 15.5
 - Version 1.4.0 Build 60

**Additional context**
Note the code in the screenshots is not being used as a new one was issued after.

**Comment by tijme** [comment]
Thanks for supplying a test QR code. Bug confirmed. Will work on a fix in the future.

**Comment by tijme** [comment]
Fixed in development. Closing this issue as it will be pushed to public soon (within a few weeks).
