### ISSUE TITLE
App looks for QR to scan after selecting continue manually

### ISSUE THREAD

**Issue by JCKE** [raivo-otp/ios-application#142]
**Describe the bug**
The app will continually look for a QR code with the camera even after selecting "Don't have a QR code? Continue Manually!". If you're pointing the phone at a failed QR code to enter the code manually, this is jarring as the Invalid QR Code prompt repeatedly comes up. This is unintentional behavior.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click the + in the top right corner of the app to scan for QR
2. Click the "Don't have a QR code? Continue Manually!" button
3. At the screen to enter info manually, point the camera at a QR
4. The app will try and scan the QR, even though there's no indication it is doing so

**Expected behavior**
When trying to add a code manually, the camera should stop trying to scan for QR codes.

**Screenshots**
![App-Screenshot](https://user-images.githubusercontent.com/6626801/177284920-588565cc-568d-4abb-9fd2-aab9e76415e5.jpeg)

**Smartphone:**
 - Device: iPhone SE 2020
 - OS: iOS 15.5
 - Version 1.4.0 Build 60

**Additional context**
Try with this invalid QR code (taken from wikipedia article on QR codes)

![QR_code_for_mobile_English_Wikipedia](https://user-images.githubusercontent.com/6626801/177284910-c26538fc-071d-430b-bff3-5a7396d599dc.jpg)

**Comment by Johan446** [comment]
Same here. 

So the camera is still active when you have the ‘manual insert form’ and receive an error while scanning the above qr code in the background.

**Comment by tijme** [comment]
Fixed in development. Closing this issue as it will be pushed to public soon (within a few weeks).
