### ISSUE TITLE
Support Android, Windows, macOS and Linux

### ISSUE THREAD

**Issue by dtantono** [raivo-otp/ios-application#143]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
it will be really handy for raivo to support many platforms

**Describe alternatives you've considered**
So far, we have Authy. But, not everyone likes store the phone number. 

**Additional context**

**Comment by tijme** [comment]
Hey @dtantono, unfortunately I have to close this one as I do not have the time to develop an Android, Windows and Linux client. A MacOS client already exists. Its a titlebar application that receives your OTP's securely from your mobile device, without ever storing the OTP's on your MacOS device.
