### ISSUE TITLE
No icloud sync option on ipad

### ISSUE THREAD

**Issue by theTrueEnder** [raivo-otp/ios-application#145]
I have Raivo on my iPhone, and it works great. It says it's connected to icloud, syncing, etc. I want to also have access to the OTPs on my iPad, however upon installing the app, there is no such option. The "Account" "Provider" and "Status" lines all say "None (offline)" with no apparent way to force a sync or do anything whatsoever. 
The iPad has internet access, is connected to the same icloud as the iPhone, and has not had similar issues in the past. 
Help would be appreciated (:

ipad: 10.7" 9th gen, iOS 15.5

**Comment by tijme** [comment]
Probably similar to #64, therefore closing. Let's track the progress in #64.
