### ISSUE TITLE
Local setup without a password

### ISSUE THREAD

**Issue by Avamander** [raivo-otp/ios-application#149]
**Is your feature request related to a problem? Please describe.**
I don't see a practical benefit in any scenario to require a password for local setup.

How I see things going with the currently available options:

1. I generate a random password and store it in a password manager. One possible result:
    1. I need the 2FA to unlock the password to unlock the 2FA I need to unlock the password. I certainly do not want to find myself in a situation where I have to re-enter it and I have no other devices nearby.
2. I set a password I can remember. Three possible results:
    1. A strong password. It will be long and cumbersome to enter, meaning all my authentications will be very cumbersome and it significantly increases the risk for shoulder surfing
    2. A relatively weak password that won't be as cumbersome to enter but won't offer much security. 
    3. High risk of forgetting the password if I don't have to enter it each time

**Describe the solution you'd like**
Ability to avoid setting any passwords when choosing not to use iCloud.

**Describe alternatives you've considered**
Some other app, but other iOS TOTP apps are absolutely terrible.

**Comment by tijme** [comment]
A master password is required for encryption purposes (even for your local database). If you set a strong password that you can remember you only have to enter it once (during setup) and never again. Shoulder surfing should therefore not be a problem. I recommend writing it down and storing it in a physical Vault for disaster recovery.

Unfortunately at this point in time I'm not focussing on removing the master password or PIN code functionality. Therefore I'm closing this feature request.

**Comment by Avamander** [comment]
@tijme 

Sure, but generate that key then. There's no need for me to set a password that offers no benefit at all. If the system can be trusted then the system can read the key from the filesystem and decrypt the database. If the system can't be trusted, then all is lost anyways.
