### ISSUE TITLE
Gets kicked out when opening the app

### ISSUE THREAD

**Issue by In-Woods** [raivo-otp/ios-application#152]
**Gets kicked out when opening the app**
basically i get kicked out whenever i open ravio and unlock it, with biometric or without.

 - Device: iphone 12
 - OS: IOS 15.5
 - Ravio version: 1.4.2

https://user-images.githubusercontent.com/110089058/181198523-26b49e01-fcba-4a11-80fb-d8af0965367a.mov

https://user-images.githubusercontent.com/110089058/181198554-e700db2c-4ca5-4fb4-9dc3-414913cf3d97.mov

**Comment by tijme** [comment]
Do you have iCloud sync enabled @In-Woods? If so, you can logout and login again and it should work again. I think your SQLite database is corrupt but I'm not sure. Do you have any more information? When did this start happening? Did you do anything special?

**Comment by In-Woods** [comment]
@tijme no i dont have icloud sync enabled, well the only info i can give is that what i did:-
1. installed the app
2. lunched and set a master key
3. close app 
4. open the app
5. crush
so yeah, theres no info more tha that, sorry :(

**Comment by tijme** [comment]
Could you try to setup Raivo again by reinstalling the app, and see if it works?

**Comment by tijme** [comment]
Closing as inactive.
