### ISSUE TITLE
iCloud sync 

### ISSUE THREAD

**Issue by hf-checking** [raivo-otp/ios-application#155]
**Describe the bug**
Still can’t use iCloud sync

**To Reproduce**
Turned off and on iCloud Drive
Turned off and on iCloud settings for Raivo
Turned off and on device
Completely quit Raivo and restarted 

**Expected behavior**
I hoped to sync to iCloud.

**Screenshots**
Sorry no screenshot. It’s just saying: none (offline)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 15.5

**Additional context**
I hope we can get this fixed. 
thanks

**Comment by tijme** [comment]
Is it disabled during the configuration of the app? Or have you already configured the app? You cant change the synchronisation provider after configuration.

**Comment by hf-checking** [comment]
The app is already configured. I am using it quite a while now and when I started using Raivo it wasn’t working. It was only a feature request. But now it should be, but if I understand correctly, only new installations can use the option. Or is there a way to use it? Like reinstalling?

**Comment by tijme** [comment]
That is correct. Unfortunately I have not implemented a way to change synchornisation provider after setup yet.

For now, the best option would be to make an export via settings. Make sure you're able to extract the ZIP-export and are able to view the QR-codes. 

If you can, then sign out of Raivo and reconfigure it using iCloud. You can now scan the QR-codes from the export again. Unfortunately the automated import function of the ZIP is not finished either.

**Comment by hf-checking** [comment]
Oke. Thanks. I will do that! 👍👍😁
