### ISSUE TITLE
1.4.3 all icons broken

### ISSUE THREAD

**Issue by valynor** [raivo-otp/ios-application#158]
Hey,

just updated to 1.4.3, all icons are gone/showing a placeholder. 
Editing an entry and trying to select an icon from the icon repository throws a bad URL error.

**Comment by valynor** [comment]
Well actualllllly ... turns out my DNS resolver blocks NRDs (newly registered domains, less than 1 months old). :)

**Comment by tijme** [comment]
Oh wow, this is an interesting edge case I hadn't concidered.

Glad that you shared this. How did you find out about the root cause?

Which DNS resolver do you use?

**Comment by valynor** [comment]
Hey tijme,

I use NextDNS.io and saw it in the log. 
"Block Newly Registered Domains (NRDs)
Block domains registered less than 30 days ago. Those domains are known to be favored by threat actors to launch malicious campaigns."
is a security feature you can enable. 
Added *.icons.raivo-otp.com to the Allow List and everything works again. :)

**Comment by tijme** [comment]
I should have used the default Github subdomain for the icon repository. Great feedback!
