### ISSUE TITLE
One-time passwords not showing on Mac even after linking it to app on iOS several times.

### ISSUE THREAD

**Issue by rembal1230** [raivo-otp/ios-application#159]
**Describe the bug**
One-time passwords not showing on Mac even when all the iCloud setting are set correctly and even when I linked the iOS app to Mac app correctly several times. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Receivers'
3. Link Mac with scanning the QR code
4. Nothing happens on Mac
![001](https://user-images.githubusercontent.com/110897827/183614687-881c9bb1-64cc-45b4-8150-6926c3a6b547.PNG)

![002](https://user-images.githubusercontent.com/110897827/183614978-1d20fe09-5fae-4b04-94b9-d836cff867e5.jpg)

**Expected behavior**
One-time passwords showing on Mac app

**Smartphone (please complete the following information):**
 - Device: [iPhone12Pro]
 - OS: [iOS15.6]
 - Version [19G71]

**Additional context**
Desktop
- Device: [MacBookAir(M1, 2020)]
- OS: [MacOSMonterey12.5]
- Version [21G72]

**Comment by rembal1230** [comment]
Raivo is enabled in iCloud account settings

**Comment by rembal1230** [comment]
I also restarted the app and Mac 6 times and still nothing.

**Comment by tijme** [comment]
Is it just the notification? As in, is your clipboard on MacOS filled with the seed or not?

**Comment by rembal1230** [comment]
omg im so stupid hahah let me delete this post sorryt and thanks for help,. everything works as it should

**Comment by tijme** [comment]
Could you explain what happened? Would be nice to help others if they experience the same problem.

**Comment by rembal1230** [comment]
I forgot that this app on mac only copies the code from iOS app and gives you notification that it is copies to clipboard. I thought I would get the same interface on mac as I have on iOS.
