### ISSUE TITLE
Alternate icons not working on iPadOS

### ISSUE THREAD

**Issue by geodelis** [raivo-otp/ios-application#161]
Hi there!

I wanted to ask if there is a reason that you cannot change the app icon for Raivo on iPadOS. I know you can change it in iOS, so I am not sure if it is a bug or not.

Thanks in advance!

**Comment by tijme** [comment]
This seems to be a bug, thanks for reporting!

**Comment by tijme** [comment]
Fixed in version 1.4.6. This will be pushed to the App Store within a few weeks.
