### ISSUE TITLE
Weak Password Prompt When Entering Wrong Backup Password

### ISSUE THREAD

**Issue by mjarzy** [raivo-otp/ios-application#162]
**Describe the bug**
When restoring from a backup and typing in a incorrect password, a weak password prompt appears. 

**To Reproduce**
1. Reinstall Raivo
2. Select Apple iCloud as a storage provider
3. Enter a password that contains only letters, no numbers or special characters

**Expected behavior**
A prompt informing the user that an incorrect password has been entered. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16 Dev Beta 6
 - Version: 1.4.4

**Additional context**

**Comment by tijme** [comment]
Will be fixed ASAP. Expect the fix to be available in the App Store in a few days.

**Comment by tijme** [comment]
Fixed in release https://github.com/raivo-otp/ios-application/releases/tag/build-67, which will be published to the App Store after review by Apple.

**Comment by tijme** [comment]
Closing this as it will be fixed/pushed to the App Store after Apple's review (expected tomorrow or the day after). Thanks for reporting this so quickly @mjarzy!
