### ISSUE TITLE
Raivo's icon repository is not working, no icons.

### ISSUE THREAD

**Issue by BwntyHntr** [raivo-otp/ios-application#163]
**Describe the bug**
Raivo's icon repository is not working, an SSL error.

**To Reproduce**
1. Go to Raivo App
2. Click on + to create a new entry and scan QR Code
3. You will find that the Icon Photo is empty
4. If you click on it and try to get an Icon from the repository, it says “Refreshing Failed: An SSL Error has occurred”

**Expected behavior**
Shows a list of Icons to choose from.*

**Screenshots**
![photo1661377628](https://user-images.githubusercontent.com/81967491/186529603-96009e36-e54b-44bc-b8d4-48dccf9d5cdb.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.6.1
 - Version 1.4.5 Build-67

**Comment by tijme** [comment]
Please fix ASAP? Please mind your words. This is an open-source project published for free.

![image](https://user-images.githubusercontent.com/5873573/186598627-7bccb112-c758-4e3e-ba6b-b72b6aad77a4.png)

The certificate is perfectly valid. Are you on a corporate network with TLS interception? Do you experience it on multiple devices? I need some more info to trace the issue.

**Comment by BwntyHntr** [comment]
> Please fix ASAP? Please mind your words. This is an open-source project published for free.
> 
> ![image](https://user-images.githubusercontent.com/5873573/186598627-7bccb112-c758-4e3e-ba6b-b72b6aad77a4.png)
> 
> The certificate is perfectly valid. Are you on a corporate network with TLS interception? Do you experience it on multiple devices? I need some more info to trace the issue.

Wow didn't think fix it ASAP would be offensive but OK, my bad.

I'm not using a corporate network, just regular home wifi.

I've tried it on 3 devices just to be sure and I installed and Uninstaller the app multiple times because I didn't want to waste anyone's time.

Perhaps there is a restriction on middle eastern countries? Because after you mentioned corporate network I turned on Nord VPN on USA to do some testing and now it works. but once I turn off the VPN it shows the same error.

I didn't test other countries.

**Comment by BwntyHntr** [comment]
Found the culprit

![Screenshot_20220825-122219_Brave.png](https://user-images.githubusercontent.com/81967491/186627730-2ef2bd4b-2b52-45da-afde-022b6138fa52.png)

NextDNS (DNS AdBlocker) was blocking the domain because it was created in under 30 days.

Sorry about the confusion.
