### ISSUE TITLE
Instagram no QR code only manual key...

### ISSUE THREAD

**Issue by Yolakalemowa** [raivo-otp/ios-application#164]
**Describe the bug**
Hi, I'm sorry I'm a noot tbh and don't know if this is the right place to ask this! 

I'm trying to set up 2FA on Instagram but it doesn't provide QR code method, rather it gives a key to enter manually in the auth app. However, I don't know where in Ravio to input this key. Does it go in the secret/seed field? I don't want to try it before checking here cause I locked myself out of accounts before and I became paranoid!

**To Reproduce**
1. Go to IG > Account > Security > Setup 2FA > Here it will ask you to save your IG password in Apple passwords, but I don't want to do that I'd rather stick to Ravio so > click "Set up another way". Here you will find the manual key.

**Smartphone (please complete the following information):**
 - iPhone7
 - iOS 15.6.1

Thank you so much for your assistance! If this is the wrong place to ask this please kindly redirect me!

**Comment by tijme** [comment]
I don't have instagram myself, but if it's a secret key you can put it in the secret field indeed. Afterwards, Instagram will require you to verify the OTP's by entering one, before 2FA is enabled in your account. So that will allow you to check if it's the correct key.

**Comment by Yolakalemowa** [comment]
thank you it worked! And that was super fast response <3 

while I have you... better to change default algorithm to SHA256 OR 512 no? or doesn't really matter

**Comment by Yolakalemowa** [comment]
@tijme 

thank you it worked! And that was super fast response <3 

while I have you... better to change default algorithm to SHA256 OR 512 no? or doesn't really matter

**Comment by tijme** [comment]
Awesome! It's best to keep the default (SHA1) as the other algorithms are not supported by services such as Instagram most of the time.
