### ISSUE TITLE
Frequent requests for authorization

### ISSUE THREAD

**Issue by lookfirst** [raivo-otp/ios-application#166]
**Describe the bug**
First off, thanks for this wonderful software. I've happily moved over from Authy.

I've installed Raivo on my mac desktop via the app store. I've also installed the menubar app too. When I have the Raivo app open on my desktop, every X minutes, I get a notification asking me to put in my password. I assume this is wanting to sync to iCloud?

My expectation would be to see this happen maybe once at startup of the app and then not again for quite some time. Right now, it is happening too frequently.

Heck, I just got the dialog again while writing this issue...

Apologies for filing this here... not sure if this is the best place or not. It may make sense to open up a central issues project to make this more clear.

**To Reproduce**
Keep Raivo app open on OSX Desktop

**Expected behavior**
Unlock once?

**Screenshots**

![2022-08-30 at 17 33 11](https://user-images.githubusercontent.com/85355/187505352-8bddc76b-f704-4cc6-bf84-a90ed970e982.png)

**Smartphone (please complete the following information):**
![2022-08-30 at 17 35 43](https://user-images.githubusercontent.com/85355/187505493-a3a53588-9c80-4a62-8da1-c628416fb33e.png)

**Comment by tijme** [comment]
Hi @lookfirst,

Raivo for iOS is not supported on MacOS. Therefore, I will close this issue. Hope you understand.

If you want to use Raivo on your Mac, you should really use the MacOS companion app. It's better for security reasons as well!

**Comment by lookfirst** [comment]
@tijme Thanks for the fast response. This is confusing UX though... it is available in the Mac App store and says compatible. There is no indication that I should not install or use this app. Nothing in the FAQ either.

![2022-08-30 at 23 33 57](https://user-images.githubusercontent.com/85355/187561688-0abef3d8-1ed4-47d4-b05f-632604167308.png)

**Comment by lookfirst** [comment]
It is also really convenient to be able to not have to open my phone.

**Comment by tijme** [comment]
Hmm, someone filed a similar issue in the past. I just wasn't really aware that you could download it like that from the App Store. Sorry for the confusion. Could this be because you have an M1 Macbook?

Anyhow, I'll try to see if I can disable it somewhere. Or maybe enable it and make it available for MacOS as well.

The reason that I created a companion app for MacOS, instead of a fully-fledged app, is because of security reasons. The companion app does not store the seeds on your MacOS device. So if someone breaches your MacOS device, they won't be able to extract all of your OTP seeds. 

Hope that clears things up a bit.

**Comment by lookfirst** [comment]
@tijme Please don't disable it in the app store.

Yes, M1 Max 16, per the screenshot above.

The way that Authy gets around this is that it has UX to disable adding additional "devices" (or instances of the app), unless you enable it. They have a desktop app, but it sucks... pretty sure it is Electron based... a big part of the reason why I finally made the effort to switch to your excellent work.

If someone breaches my laptop, I have bigger issues than just the seeds. But at the same time, I can remotely disable things (Find My), so I'm not that worried about it.
