### ISSUE TITLE
Different Values when export and import.

### ISSUE THREAD

**Issue by dantehemerson** [raivo-otp/ios-application#168]
**Describe the bug**

When I export an OTP code and import again using the QR code, the items don't have the same logo or account.

**To Reproduce**
1. Export OTP codes. 
2. Import again one of the codes exported.
3. Then the imported value(first item in the image) is slightly different than the exported item(second item in the image)
![Screenshot from 2022-09-11 23-16-18](https://user-images.githubusercontent.com/18385321/189573053-930a24d3-2504-494c-bad0-3d36ccd6c7f2.png)

**Expected behavior**
The imported item should have the same logo and account name as the exported.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS15.6.1]
 - Version [e.g. 1.4.5(build-67)]

**Additional context**

**Comment by tijme** [comment]
Hi @dantehemerson,

About the icon, that's correct. Icons are not part of the TOTP protocol URI's. But I guess I can add it myself in the future.

About the account/issuer issue. I can't replicate it. My username is copied just fine. Is this reproducible for you?

**Comment by tijme** [comment]
Closing as inactive.
