### ISSUE TITLE
Storage of backup codes

### ISSUE THREAD

**Issue by iamGavinJ** [raivo-otp/ios-application#174]
**Is your feature request related to a problem? Please describe.**
* While I'm subscriber to Bitwarden, I do not use its OTP functionality to maintain an air gap. i.e. If Bitwarden is compromised, then malicious actors only have part of the information they need to compromise my accounts and I have a window of opportunity to slow them down.

* To maintain that separation, I also do no store backup codes in Bitwarden, and would ideally prefer to keep them in Raivo.

**Describe the solution you'd like**
* In the item edit screen (or another screen) I'd like the ability to paste, or even better use the camera and OCR in, the table of backup codes.
* A swipe action and button on the item would be ideal to reveal the backup codes.  Clicking on the code would toggle it greyed-out for used, or toggle again to "available" in case of accidental toggle.

**Describe alternatives you've considered**
Storing elsewhere.

**Additional context**
N/A

**Comment by tijme** [comment]
Hello @iamGavinJ,

I thought about this feature. Someone actually submitted it a while ago. However, I do not plan on implementing this. Backup codes should be printed on paper (and stored in a physical vault).

**Comment by iamGavinJ** [comment]
Fair point ;)
