### ISSUE TITLE
Icon Repository

### ISSUE THREAD

**Issue by Likely0938** [raivo-otp/ios-application#176]
Hi!
Love the app! Though, I can't seem to get things right in adding the icon into the repository, I am not tech savvy enough to add it into github. 

I tried following the instructions, but seem to be stuck at uploading the file. it just does not allow me to. 

Here is the file I am trying to upload. it's for BINGX.COM
![Bingx](https://user-images.githubusercontent.com/115348739/194704020-0bf41074-6713-42e8-b211-f5677ae5881f.svg)

Thank you!

**Comment by tijme** [comment]
Hello, unfortunately I do not accept icons as Github issues at the moment. At the moment, the only way to add an icon is to make a pull request. I hope to improve this in the future.
