### ISSUE TITLE
Missing accounts

### ISSUE THREAD

**Issue by peter-lxc** [raivo-otp/ios-application#178]
Had a lot of accounts created and found out not all of them where been synced to iCloud and where only local to the iPhone I had created them on

**Comment by tijme** [comment]
Can you try re-signing in to Raivo and leaving the app open for a minute? Everything should be synced. If something wasn't synced on your old device, you would have seen it as the unsynced items would be marked.

**Comment by tijme** [comment]
Hope this helps! Of course, don't forget to make a backup!

**Comment by tijme** [comment]
Closing as inactive.
