### ISSUE TITLE
Time Sync issue

### ISSUE THREAD

**Issue by Terrast** [raivo-otp/ios-application#179]
Hello, 
For security reasons, I changed my phone's timezone (IOS) to another country and adjusted the time manually since IOS apps can access my phone's timezone and therefore my location even when my VPN is on. So there is no other way. On the other hand, every time I need to use an OTP code since the time is not synced to the timezone, the code does not work and I need to set the timezone to automatic, use the code and adjust it manually again. 
Now I want to know except for changing the protocol from TOTP to HOTP, is there any way to solve this problem?

**P.S.** I couldn't find any option in Ravio's settings to sync in-app time manually or something like that.

**Comment by tijme** [comment]
Hello. Unfortunately this option is not built into the app. I'm not planning on adding this in the future because it is such an edge case. Sorry :/
