### ISSUE TITLE
Missing icon from Raivo's icon repository (issuer-icons) in ios app

### ISSUE THREAD

**Issue by Rchtr** [raivo-otp/ios-application#181]
Hello,

i cannot find the icon postgresql in the iOS App. Although it is correctly merged in the master branch of issuer-icons.
[https://github.com/raivo-otp/issuer-icons/tree/master/vectors/postgresql.org](url)

**Comment by tijme** [comment]
Seems like it didn't have the .svg extension. I've updated it for you: https://github.com/raivo-otp/issuer-icons/commit/d4eba08803b38dbd2221d95b9baac0777aa320eb.
