### ISSUE TITLE
Forgot encrypted password

### ISSUE THREAD

**Issue by mkwsin** [raivo-otp/ios-application#186]
Hi, how can I recover my encrypted password ? I export a backup file to zip, but I forgot my encrypted password I tought I had it but no, so im stuck with the zip and also in the future, Im scared that it will log out and that I have to log back with the encrypted password.
You should also put a reminder of every 2 weeks for the encrypted password, it will be great

**Comment by tijme** [comment]
If you forgot your master password there is no way to recover it. Only thing you can do is manually screenshot all qr-codes by swiping on the OTP's. You can them scan them using a fresh app installation.
