### ISSUE TITLE
Incorrect Recovery Key

### ISSUE THREAD

**Issue by waaww** [raivo-otp/ios-application#187]
For whatever reason, my recovery key is incorrect. Is there a way to reset this because I copied the key when I first received it a few months ago so there’s no change of copying it wrong. I’m trying to set the app on my 2nd device.

**Comment by waaww** [comment]
Hello, I’m still getting that the password is incorrect. Is there anything someone can do because I copy and pasted the key to avoid this happening.

**Comment by tijme** [comment]
Hello @waaww,

Raivo OTP doesn't provide you with a master password. You had to enter it yourself during the setup. If you forgot your master password there is no way to recover it. Only thing you can do is manually screenshot all QR-codes by swiping on the OTP's. You can them scan them using a fresh app installation.
