### ISSUE TITLE
How to migrate from Authy these days

### ISSUE THREAD

**Issue by jonschlu** [raivo-otp/ios-application#19]
The README.md contains a link to a manual on how to switch from Authy to Raivo. Unfortunately, the solution requires Google Chrome (I don't want to install or use Google software) and the Authy Chrome Extension, which has been EOL for quite some time now.

Therefore, I'd like to ask if there is a different and up-to-date way to migrate from Authy to Raivo. It would be great if that solution would replace the info in README.md.

**Comment by tijme** [comment]
Currently, there is no other way than to use a Chromium extension. This can be done via either Chrome or Microsoft Edge. Unfortunately Authy does not support exporting tokens in any other way.
