### ISSUE TITLE
Ability to transfer all tokens to a new Raivo device with a single QR code import facility

### ISSUE THREAD

**Issue by geekpete** [raivo-otp/ios-application#190]
**Is your feature request related to a problem? Please describe.**
Forgot my master password but still have access to the app to see all tokens including each token's QR code.
So was able to get all my existing tokens exported one by one using the QR code for each and adding to an alternate device running Raivo (or whatever auth app that can import QR codes).

**Describe the solution you'd like**
I had to import the QR code for each token one by one, it'd be cool to have this ability in a single step with a single QR code that Raivo understands to do a mass import.

**Describe alternatives you've considered**
Alternatives might be the ability to do an unencrypted export, but this has lots of downsides...

**Additional context**
Another consideration here is that it can make the ability for someone to steal all your codes MUCH easier, so probably would need an extra level of verification to use this feature (that isn't the master password, as that would prevent the feature solving the use case I used it for, but maybe biometric verify would be good.) Give the user a choice perhaps of using one or the other?

**Comment by tijme** [comment]
Hello @geekpete,

I've chosen not to implement this. I've implemented a ZIP-import function instead. Both ZIP-export & import are now available. Only requirement is that you know your encryption password.
