### ISSUE TITLE
TestFlight

### ISSUE THREAD

**Issue by rweckhoff** [raivo-otp/ios-application#191]
TestFlight beta expired ... I uninstalled and deleted the iCloud data but still not able to use app as it tells me to upgrade and it is not downward compatible.

Since I deleted iCloud data - I was not expecting this behavior.  How to I reinitialize as new?

**Comment by Fuderal** [comment]
same issue here

**Comment by itsmichaelyu** [comment]
I also am having this problem.

**Comment by tijme** [comment]
I'll make sure to push a new version to TestFlight today, so you can update via TestFlight tonight or tomorrow. That's a temporary fix.

For a more permanent fix I'll take a look at how I can improve the downgrade/upgrade process.

**Comment by tijme** [comment]
Build is currently in review by Apple TestFlight: https://github.com/raivo-otp/ios-application/releases/tag/build-69

**Comment by tijme** [comment]
TestFlight version is not yet released, but Apple did just release the latest version 1.4.6 in the AppStore. So if you install the AppStore version you should be good again 🚀
