### ISSUE TITLE
App for Apple Watch

### ISSUE THREAD

**Issue by estavick-crypto** [raivo-otp/ios-application#192]
Requesting an app for Apple Watch. Having an app on a watch displaying OTP codes will definitely be more convenient than grabbing your iPhone (especially if you happen to be charging your phone and you’re like 20 feet away, for example). I will be supporting the developer and will even be more supportive when this happens.

**Comment by Felting** [comment]
Yes, this would be very useful

**Comment by tijme** [comment]
Duplicate of #17, will track in that issue.
