### ISSUE TITLE
Sharing Raivo Access

### ISSUE THREAD

**Issue by Sirty85** [raivo-otp/ios-application#196]
Good evening,

Is there a way I could share my Raivo access with my spouse?  They often have to ask me for the code to access a site and I thought if it was possible for them to see what I see, that would be helpful.

Thanks!

**Comment by 0ptim** [comment]
You could just have her download raivo or an alternative OTP app. Then you give her the secrets for the Logins she needs so she can generate the codes as well on her phone.

**Comment by Sirty85** [comment]
Perfect, that worked exactly how you described.  Thanks!
