### ISSUE TITLE
Don‘t find the iCloud synchronisation folder

### ISSUE THREAD

**Issue by Fragmichmal** [raivo-otp/ios-application#217]
**Describe the bug**
I can‘t find the iCloud synchronisation folder. 

**To Reproduce**
1. activate „Raivo“ in settings - iCloud - apps
2. Open iCloud folder

**Expected behavior**
There is a folder for the synchronization of OTP codes

**Smartphone (please complete the following information):**
 - Device: iPhone 13mini
 - OS: 16.3

Best regards

**Comment by tijme** [comment]
They are not visible in your iCloud GUI because they're stored in CloudKit: https://developer.apple.com/icloud/cloudkit/.
