### ISSUE TITLE
Not syncing 

### ISSUE THREAD

**Issue by peter-lxc** [raivo-otp/ios-application#223]
**Describe the bug**
I have updated both my iPad and iPhone to the latest iOS and app version, I add a new OTP to my iPad and it does not sync to my iPhone

**To Reproduce**
1. Add a new OTP on iPad
2. Checked sync status says synced to iCloud 
3. Go to iPhone check sync status says sync
4. Code added in step 1 not visible 

**Expected behavior**
Code to be visible on other devices

**Screenshots**

**Smartphone (please complete the following information):**
 - iPhone 14 pro max
 - ios 16.3.1
 - Version 1.4.8 build 70

**Additional context**
If I enable debug logging on my iPad I am unable to export the log its crashes the iPad app

**Comment by zachtywebb** [comment]
I posted the same issue under [https://github.com/raivo-otp/ios-application/issues/220](https://github.com/raivo-otp/ios-application/issues/220)

**Comment by tijme** [comment]
Thank you for reporting this indeed. I'm closing this so it can be tracked in #220.
