### ISSUE TITLE
Need help resetting Raivo

### ISSUE THREAD

**Issue by MerMan105** [raivo-otp/ios-application#224]
Hi. I lost my master password and want to start Raivo over. However, every time I click to delete my data and start over, Raivo asks me to enter the password because I’ve used it before. 

I can’t find any files on iCloud so tokens are all gone.

how can I use Raivo again?

thanks!

**Comment by tijme** [comment]
It should delete all data, this is not happening for you? Does Raivo show any data for you in the settings app? And can you delete that dat?
