### ISSUE TITLE
What’s Raivo do exactly?

### ISSUE THREAD

**Issue by cmmay23** [raivo-otp/ios-application#227]
I saw an article online about  Raivo…however I’m not sure if I need it or not.

I use mostly my iPad Air or Mac mini or iPhone 13.  I have LastPass, and Identity Force and have 2fa on as many things as offered it seems.

do I need Raivo?  I guess I don’t have a good understanding of what it does.

**Comment by tijme** [comment]
https://raivo-otp.com/faq/
