### ISSUE TITLE
After the app reset it still asks for a password 

### ISSUE THREAD

**Issue by polacky** [raivo-otp/ios-application#229]
Once I reset Ravio due to forgotten password, it still asks for a passcode 

**To Reproduce**
1. Open app>continue >in the storage select Apple iCloud 
2. Click on Continue 
3. From password screen click on “I forgot my password”
4. On the next screen click on “delete all my data”
5. Click Yes if asks “are you sure “
6. Once the screen refreshes return to step 1

**Expected behavior**
After the app reset it should ask to create a new password instead of the password from the previous iteration.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone11 pro max]
 - OS: [ iOS16.3.1]

**Additional context**

**Comment by tijme** [comment]
Confirmed this bug. Will be fixed in the next verison.

**Comment by tijme** [comment]
Version reference: 1.4.11 (build-73).
