### ISSUE TITLE
Passcode attempts

### ISSUE THREAD

**Issue by CJL16** [raivo-otp/ios-application#232]
Hi - I'm new to Raivo and really liking it having switched from Google.  I was pleased to see that there is a limit to the number of passcode attempts allowed if FaceID fails but it's not clear to me what happens if I use up my 6 attempts?  What's the process here?

As an aside, I really like the Zip option for backup and good to see AES256.  In my opinion, it's better than a cloud sync as it leaves me more in control.

Thanks for the great product - Chris

**Comment by tijme** [comment]
Thanks Chris! Whenever you reach the 6 attempts you have to wait for X amount of seconds, where X increases per incorrect try. X is reset to zero whenever you enter the correct passcode.

**Comment by CJL16** [comment]
Hi Tijme,
Many thanks for getting back to me on that.
Very helpful and again – great app 😊

Best Regards - Chris
