### ISSUE TITLE
Incorrect code

### ISSUE THREAD

**Issue by Sovereignindividual** [raivo-otp/ios-application#235]
Hello,
I’m trying to authenticate with the 2FA Raivoo differents accounts, like email, umbrel or social networks, and the system answer is that the code is incorrect.
I don’t know why, because I didn’t change anything and now I can’t verificate nothing.

**Comment by tijme** [comment]
Make sure the time(zone) on your iDevice is set to automatic, and you don't have any other devices in your network that set time on your iDevice.
