### ISSUE TITLE
LinkedIn not synced

### ISSUE THREAD

**Issue by Flukas88** [raivo-otp/ios-application#236]
**Describe the bug**
Setting up a new iPhone, iCloud sync backup is not including LinkedIn 

**To Reproduce**
1. Sync on iCloud enabled
2. Install on a new phone

**Expected behavior**
Linkedin synced up 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 pro max
 - OS: [e.g. iOS8.1] iOS 16.3.1
 - Version [e.g. 22] 1.4.8 (build-70)

**Additional context**

**Comment by tijme** [comment]
Hmm, I cannot replicate this bug. Do you have any more information? Are you able to replicate it on another device?

**Comment by Flukas88** [comment]
I don't have another iPhone with me to test it.
I will try to manually readd it to the new phone and check if it reflects on the old as soon as I can.
Will update then

**Comment by Flukas88** [comment]
I manually added it. Since it's a one off, even if not solved, this can be closed

**Comment by tijme** [comment]
Linking this to #220
