### ISSUE TITLE
Different codes on different devices

### ISSUE THREAD

**Issue by angusmci** [raivo-otp/ios-application#239]
**Describe the bug**
I have Raivo OTP installed on an iPhone 12 and an iPad Pro. The two devices are connected to the same iCloud account, and syncing via iCloud is enabled.

I set up OTP for Namecheap on the iPhone, and can use it successfully to log in. The newly-created account shows up Raivo on my iPad. However, the codes displayed on the iPad do not match those on the iPhone, and are rejected when I try to log in.

My expectation was that syncing would allow one device to generate the same codes as the other. Is this not correct?

**To Reproduce**
1. Launch Raivo on phone
2. Click on '+' to set up a new OTP account
3. Go through onboarding flow for setup and complete account creation.
4. Go to Settings and confirm that "Syncing up-to-date" is shown for Status
6. Launch Raivo on tablet
7. Go to Settings and confirm that "Syncing up-to-date" is shown for Status
8. Check code for newly added account

**Expected behavior**
The codes displayed for the account should be identical on the two different devices.

**Actual behavior**
The codes displayed are different, and the code on the tablet device does not work.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.3.1
 - Version 1.4.8 (build-70)

 - Device: iPad Pro 10.5"
 - OS: iPadOS 16.3.1
 - Version 1.4.8 (build-70)

**Comment by tijme** [comment]
This is a timezone/datetime setting on your iPad. Did you configure your timezone correct? Is it on automatic?

Codes are incorrect if your datetime on iPad is incorrect. Must be precise on the second.

**Comment by angusmci** [comment]
Time zone is the same on both devices. Time zone on both is set to Automatic.

There doesn't seem to be an easy way to get iOS devices to show time-with-seconds, but as far as I can tell both devices are synchronized to within a second; the displayed minute on both devices changes simultaneously.

**Comment by angusmci** [comment]
OK, after deleting the app on the iPad, destroying the existing data on the phone, and recreating my accounts, the two devices now show the same codes. This process has also resolved the other bug that I reported -- account names not showing up -- so I'm going to mark that as closed too.
