### ISSUE TITLE
Local backup 

### ISSUE THREAD

**Issue by natefear** [raivo-otp/ios-application#24]
Love the app just wish there was an option to save the backup files locally to the files app or iCloud rather than exporting by email?

Had ago at trying to copy and save the zip from the generated email but IOS wouldn’t permit it :(

**Comment by tijme** [comment]
The reason I built it like this is so I can inform people (via the mail) that the ZIP-archive is AES encrypted and can't be decrypted via the default MacOS/Windows extraction utilities.

However, maybe I can build some other features to inform users. Maybe in a screen before exporting the ZIP-archive.

Good idea!

**Comment by tomatotango** [comment]
Second this request. Please implement a local backup feature!

**Comment by DesignatedJM02** [comment]
I am having an issue. Not sure if what you commended is related. But here is my issue. I setup the app with a strong password. Saved that password. Then once I was done moving my logins to Raivo I then exported my stuff to a zip. I got it into iTunes from my phone and then dragged the .zip to my Windows desktop for my various backing up processes. I tested the .zip by attempting to extract the files using 7Zip and using the same password that I had setup and saved earlier. I got a Password incorrect error. Same thing with WinRar. I was however able to extract the files via my Phone.

Is this intentional? If so, I have no issue with it as that adds a layer of security as not being able to be decrypted very easily. But I am just curious if this issue and your reply, also applies to my issue as well. 
Thank you.

**Comment by tijme** [comment]
> I am having an issue. Not sure if what you commented is related. But here is my issue. I setup the app with a strong password. Saved that password. Then once I was done moving my logins to Raivo I then exported my stuff to a zip. I got it into iTunes from my phone and then dragged the .zip to my Windows desktop for my various backing up processes. I tested the .zip by attempting to extract the files using 7Zip and using the same password that I had setup and saved earlier. I got a Password incorrect error. Same thing with WinRar. I was however able to extract the files via my Phone.
> 
> Is this intentional? If so, I have no issue with it as that adds a layer of security as not being able to be decrypted very easily. But I am just curious if this issue and your reply, also applies to my issue as well.
> Thank you.

The ZIP-archive is AES encrypted and can't be decrypted via the default MacOS/Windows extraction utilities. That is why you need e.g. "The Unarchiver" for MacOS.

**Comment by DesignatedJM02** [comment]
> 
> 
> > I am having an issue. Not sure if what you commented is related. But here is my issue. I setup the app with a strong password. Saved that password. Then once I was done moving my logins to Raivo I then exported my stuff to a zip. I got it into iTunes from my phone and then dragged the .zip to my Windows desktop for my various backing up processes. I tested the .zip by attempting to extract the files using 7Zip and using the same password that I had setup and saved earlier. I got a Password incorrect error. Same thing with WinRar. I was however able to extract the files via my Phone.
> > Is this intentional? If so, I have no issue with it as that adds a layer of security as not being able to be decrypted very easily. But I am just curious if this issue and your reply, also applies to my issue as well.
> > Thank you.
> 
> The ZIP-archive is AES encrypted and can't be decrypted via the default MacOS/Windows extraction utilities. That is why you need e.g. "The Unarchiver" for MacOS. I think 7-Zip will do for windows :)

I think I figured out my issue. I made the encryption password 128 characters. 7Zip I believe only allows for somewhere around 90 or 95 characters for a password. I would think that is why it's saying that my password is incorrect when I go to extract using 7Zip. Extracting on my device works fine without issue. 

Is there a way to change the encryption password without having to redo everything?

**Comment by tijme** [comment]
This will be released in TestFlight version 1.1.16 soon. After the testing phase it will be released as public release.

https://github.com/raivo-otp/ios-application/releases/tag/build-35
