### ISSUE TITLE
raivo-otp-export

### ISSUE THREAD

**Issue by atiziman** [raivo-otp/ios-application#242]
i just exported my raivo zip and now i have to put my password BUT which one? it is good that i am testing it now because in case of emergency i would be f*** not being able to see inside my export, so please explain i would be grateful. thanks in advance andreas

**Comment by tijme** [comment]
Your master password that you used to setup Raivo.

**Comment by atiziman** [comment]
O! What a surprise! A reply😂
Anyway i dont remember having set a password at the registration Strange

**Comment by atiziman** [comment]
hello Tijme,

Ihave now insztalled the app on my m1 mac and here it asked about the encrypted password so i did
but on the iphone im pretty sure now that it did not ask for one i would have had to put one there or i was completely out of reality (can happen) but very seldom
perhaps there is a glitch in the ios software that has to be done
i didnt know that you have an option for the mac and that perhaps you have to first install on the mac and then from there to the ios i started with the ios

anywy can i import the passwords from ios to my mac or should i do all the prosessus from the beginning again?
greetings and a good night
andrea
