### ISSUE TITLE
Question regarding re-install

### ISSUE THREAD

**Issue by wilfriedgrange** [raivo-otp/ios-application#246]
Hello, suppose I remove the app from my IPhone (Icloud account) and then re install it on the very same IPhone. 

When I re-install, how can I make sure I get back all data ?

Shall I put back the same master password ? Or can I choose any pass and then it will sync automatically ?

Best

**Comment by tijme** [comment]
*If you have iCloud sync enabled (check your Raivo settings)*, then yes. Just enter your same master password and you'll get all your tokens again.

If you want to be absolutely sure, you can also make a ZIP archive export. This can later on be imported into the app. But it shouldn't be necessary.
