### ISSUE TITLE
Add User Accounts Secret Key Syncing (beyond iCloud)

### ISSUE THREAD

**Issue by lwf-mlee** [raivo-otp/ios-application#247]
**Is your feature request related to a problem? Please describe.**
_No_

**Describe the solution you'd like**
_Please provide the users an option to create a user account (independent of iCloud) and encrypt backups of secret keys so that they can be synced across platforms (perhaps linux, windows, macos, etc). The concern is that some users can be locked out of their iCloud accounts or have it be stolen, thus preventing user access to important 2FA keys._

**Comment by tijme** [comment]
Merging this with #49. Thanks for the request!
