### ISSUE TITLE
Remove application icons with poor visual effects in iOS "dark mode"

### ISSUE THREAD

**Issue by f2sky** [raivo-otp/ios-application#249]
Some **application icons** are almost unrecognizable in the "**dark mode**". It is recommended that this experience be optimised.
The method for viewing poor icons is as follows:

1. Open the "dark mode" of the iOS system;
2. Open the "edit" mode of any saved entry and browse or search for icons based on keywords, such as "GitHub";

<img width="375" alt="IMG_59741" src="https://user-images.githubusercontent.com/8769077/234740395-6e64aa2d-60f7-494f-84f9-2f4682eb0b1c.png">

3. When not searching based on keywords, all icons that are almost unrecognizable in "dark mode" can be browsed.

**Suggestions:**
1. Remove or replace these bad online application icons;
2. Add a new feature: allow users to DIY upload their own chosen application icons (not dependent on built-in icons);
4. Add a new feature: allow users to use simple "text + background color" as application icons.

**Comment by tijme** [comment]
Tracking this in #205. Idea is to apply a default effect in dark mode that makes the images lighter, so they are always visible, even if they have black colors.
