### ISSUE TITLE
Allow biometric as default login method

### ISSUE THREAD

**Issue by alexkwa** [raivo-otp/ios-application#25]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to tap on the link to use biometric login.

**Describe the solution you'd like**
There should be an option to use a certain method as default. Specifically, in the settings whete TouchID unlock is on, another option appears that says something like "Make default".

**Comment by tijme** [comment]
I supposed the "TouchID to unlock" option was the default when opening Raivo OTP. At least that counts for the FaceID. Whenever I open Raivo OTP, the FaceID popup is shown and Raivo OTP is unlocked.

Doesn't this work for TouchID?

**Comment by alexkwa** [comment]
I troubleshooted a little more and it looks like it is default on startup. But, the TouchID verification doesn't appear by default if the app locks after the Inactivity Lock has activated.

**Comment by tijme** [comment]
It turned out to be the expected behaviour. I changed it in commit a096f70e8ac0fcaf6dd15a79acad8faa093d8116. Works as you requested now.

**Comment by tijme** [comment]
This issue will be fixed in release 1.1.11 which will be pushed to TestFlight as soon as Apple approves it.
