### ISSUE TITLE
Import button not working

### ISSUE THREAD

**Issue by forte97** [raivo-otp/ios-application#251]
**Describe the bug**
Pressing the import button does nothing

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Import OTPs from ZIP archive'
3. Click on the red 'Import' button
4. Nothing happens.

**Expected behavior**
It asks me for the ZIP file.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.3
 - Version 1.4.10 (build-72)

**Additional context**

**Comment by tijme** [comment]
Hmm, interesting. I'm not able to reproduce this at the moment. Maybe @z64me has an idea what could be going on here?

**Comment by tijme** [comment]
Closing as inactive.
