### ISSUE TITLE
Unable to delete duplicate entries

### ISSUE THREAD

**Issue by eh8to** [raivo-otp/ios-application#252]
**Describe the bug**
I accidentally scanned the QR code twice and now have duplicate entries that display the same tokens. When I swipe left and try to permanently delete either entry, it would get deleted but pop right back to the same location shortly after (0.5 seconds).

**To Reproduce**
1. Go to 'Passwords'
2. Swipe left on 'Nintendo Account' in my case
3. Permanently delete

**Expected behavior**
For the swiped entry to be removed.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11 Pro]
 - OS: [e.g. iOS16.5]
 - Version [e.g. 20F5039e]

**Additional context**

**Comment by splashofoliveoil** [comment]
Had the same problem earlier. 
Solved it by freeing up some space on iCloud (which was full). After doing so, I was able to delete the duplicate entry without it reappearing. 
Hope this helps 👍

**Comment by tijme** [comment]
Thanks for the info @splashofoliveoil. This fixes it indeed.
