### ISSUE TITLE
How to restore from iCloud backup?

### ISSUE THREAD

**Issue by seldenr** [raivo-otp/ios-application#253]
I used Raivo on an iPhone with iCloud backup/sync. After my phone was taken and smashed, I got a new one and set it up under my Apple ID and restored from iCloud backup. However Raivo does not prompt me to restore my accounts (I just get a prompt to set a master password). 

Am I missing something? How can I restore those accounts?

**Comment by seldenr** [comment]
This is app version 1.4.10

**Comment by tijme** [comment]
If you're restoring, you first need to login with THE SAME iCloud account on your new iPhone. Afterwards, start Raivo and tap on iCloud Sync Provider. You'll get a screen that you've previously used Raivo and that you need to enter your previously set master password. Once you do this and login, your OTP's will be retrieved from iCloud.

**Comment by seldenr** [comment]
That’s exactly the issue though - I am on the exact same iCloud account, but when I tap the iCloud sync provider I am prompted to set a new master password. Is there any way to recover that iCloud data is Raivo isn’t picking it up? All my other apps are recovering immediately

**Comment by juweissenberg** [comment]
@seldenr I am facing the same issue, did you ever find a solution?
