### ISSUE TITLE
I can't install on Mac 

### ISSUE THREAD

**Issue by InquisitiveONE2** [raivo-otp/ios-application#254]
My Mac has the latest system version, but yet when I try to run Raivo it tells me my Mac (13.3.1) needs the latest software system.  What do I need to do to make Raivo work?
thank you

**Comment by tijme** [comment]
You cannot install Raivo for iOS on MacOS. Please refer to the [MacOS application](https://apps.apple.com/app/raivo-otp/id1498497896). It requires macOS 12.0 or later.
