### ISSUE TITLE
Biometrics does not initially work after transferring to a new phone

### ISSUE THREAD

**Issue by carycodes** [raivo-otp/ios-application#255]
**Describe the bug**
After transferring data to a new phone, Raivo still thinks that Face ID has been enabled (I assume this is the same with Touch ID, but haven't tested), but it has not requested Face ID access on the new phone, so the feature doesn't work.

**To Reproduce**
1. Install Raivo on iPhone A, and enable Face ID.
2. Obtain a new/clean iPhone B.
3. Transfer your data from A to B (I used the direct bluetooth method, not sure if this matters)
4. Attempt to unlock Raivo on iPhone B using biometrics
5. Notice that it doesn't do anything, even when you click the "unlock with biometrics" button.
5.b. Notice that Face ID is enabled in the Raivo settings

Workaround: manually disabling and re-enabling Face ID causes Raivo to correctly request the necessary permission on the new phone, and things go back to working.

**Expected behavior**
When the user attempts to use biometrics, Raivo should detect if it does not have permission to use biometrics, and should (re)request it as needed.

**Smartphone (please complete the following information):**
Pretty sure this doesn't matter, but I'll fill it out anyway
 - Device: iPhone X transferring to iPhone 13 mini
 - OS: iOS 16.4.1 (latest as of right now)
 - Version: 1.4.10 (build-72)

**Comment by tijme** [comment]
Interesting case. Did this crash the app as well?

**Comment by carycodes** [comment]
It did not crash the app for me—tapping the “unlock with biometrics” button simply didn’t do anything.
