### ISSUE TITLE
Issuer icons appear in the github repository but not in Raivo app

### ISSUE THREAD

**Issue by gkarag** [raivo-otp/ios-application#256]
**Describe the bug**
I have added recently an issuer icon for ziggo.nl. When I go to the master branch of issuer-icons I can see the file `vectors/ziggo.nl/ziggo.svg` exists and I can open and display it. But when I go to the Raivo app and try to find the same icon in the "Raivo's icon repository", it fails to appear there. I have tried refreshing the list with no luck.

**To Reproduce**
1. Go to the list of saved 2FA and try to change the issuer icon of any of them
2. Click on 'Raivo's icon repository' when prompted
3. Scroll down to the end of the icons' list or search "ziggo"
4. The icon does not appear and cannot be found

**Expected behavior**
I would expect an issuer icon that already appears in the github repository to appear in the application's "Raivo's icon repository".

**Screenshots**
n.a.

**Smartphone:**
 - Device: iPhone14Pro, iMacM1
 - OS: iOS16.4.1, macOS 13.3.1
 - Version 1.4.10

**Additional context**
n.a.

**Comment by tijme** [comment]
Should be fixed now

**Comment by gkarag** [comment]
I confirm. Thanks a lot!
