### ISSUE TITLE
Translation - multiple languages

### ISSUE THREAD

**Issue by Morse6690** [raivo-otp/ios-application#257]
**Is your feature request related to a problem? Please describe.**
This seems like the best otp app I have used on ios, especially now that importing is now supported. However the user base could increase substantially if other languages were supported. 

**Describe the solution you'd like**
Please translate the app into other languages. 
Some open source apps use the weblate platform to allow users to contribute to the translation. 

**Describe alternatives you've considered**
None 

**Additional context**
None

**Comment by tijme** [comment]
Nice one. Would love to implement this in the future!

**Comment by Betacart** [comment]
I am volunteer for Czech language. Count me in!

**Comment by nicopasla** [comment]
I can help in French

**Comment by tijme** [comment]
Awesome people. For this feature I will have to make a base file for the translations, which can then be translated. Hopefully I can implement that in one of the upcoming versions.
