### ISSUE TITLE
Blurring app screen in switch mode

### ISSUE THREAD

**Issue by donBarbos** [raivo-otp/ios-application#261]
**Is your feature request related to a problem? Please describe.**
I see all the information and codes in the application when I move to switch mode

**Describe the solution you'd like**
I want to use blurring in app when it switch.

**Describe alternatives you've considered**
None

**Additional context**
Like Google Authenticator and some financial app where need to hide information.

**Comment by donBarbos** [comment]
+ this will quickly hide information from an outside observer if you are used to going into switch mode

**Comment by tijme** [comment]
Will be implemented in the next release. A bit in a different form than blurring. It will just hide all content on the screen and show an empty Raivo screen.

**Comment by tijme** [comment]
Version reference: 1.4.11 (build-73).
