### ISSUE TITLE
No way to reset master password

### ISSUE THREAD

**Issue by Arvind-Srinivasan** [raivo-otp/ios-application#262]
**Is your feature request related to a problem? Please describe.**
I have currently forgotten my master password to the app, but I am able to login and view every OTP account and QR code. I currently know both my pin and biometrics to be able to do so.

**Describe the solution you'd like**
I would like the ability to reset the master password using both the pin and biometrics or alternatively (with many warnings) export a zip with encryption being my pin. This unsafe zip could then be used after resetting the application and loading the TOTP codes back in (and setting a new master password) and promptly deleted. 

**Describe alternatives you've considered**
I could manually save every single QR code using a screenshot from my existing logged in view and then reset the application. I could then set a new master password on relaunching the application and load my passwords back in. 

**Additional context**
I currently feel that the ability to not export a zip that has little to no security (which I can later add a known password for later) is a big risk for me personally if I have no way to reset my master password.

**Comment by tijme** [comment]
Hello @Arvind-Srinivasan,

I understand your concern but I have chosen not to implement ZIP-archive exports without applying the current master password.

**Comment by Arvind-Srinivasan** [comment]
Would you be willing to export with pin instead of password?
