### ISSUE TITLE
forgot master password

### ISSUE THREAD

**Issue by vi3talogy** [raivo-otp/ios-application#263]
App is working fine but I just remembered I forgot master passwords or don't remember where i wrote it down. What should I do?

**Comment by tijme** [comment]
As by security design, you cannot recover once you've forgot your password. Best you can do is migrate your OTP's by entering your passcode in the app, then scanning all QR codes by swiping on the OTP's.

**Comment by vi3talogy** [comment]
Is there a master password when you first use the app because I do not
remember. Or is the app tied to iCloud?
