### ISSUE TITLE
How to go about factory resetting iPhone without backup from cloud.

### ISSUE THREAD

**Issue by iTurd** [raivo-otp/ios-application#264]
Hello. I tried to find an answer to my question beforehand if I had no luck. I want to factory reset my iphone. Currently I use raivo to authenticate accounts. I don't have anything attached to an iCloud account, and I plan on creating a new one when I reset the device anyways. 

I want to ensure that I don't lose the ability to access my accounts. Do I simply export then import a ZIP-archive file from the old device to the new device?

**Comment by tijme** [comment]
Yes, you can export your ZIP and then import it again after the factory reset.

**Please make sure:**
1. That you can open the ZIP file after the export (this requires your master password).
    * This should give you two files, a `.json` file and a `.html` file.
    * The `.html` file should list all of your OTP's.
2. That you've saved the ZIP to an external media (e.g. your computer).

**Comment by iTurd** [comment]
I plan to airdrop it back and forth to another iphone. Will that work? And
thanks for the reply, I appreciate it.

**Comment by tijme** [comment]
Yes 👍
