### ISSUE TITLE
Is Raivo under a new company?

### ISSUE THREAD

**Issue by jmrsn** [raivo-otp/ios-application#271]
Not a bug, feel free to remove this if needed.

Is Raivo app under a company named Mobime now? On App Store, Raivo is apparently under Mobime (which has VPN (?), keyboard, and screen recorder app). Trying to open privacy policy or developer’s website on app store lead to mobime(dot)org.

See screenshots attached.

![IMG_1581](https://github.com/raivo-otp/ios-application/assets/88580809/68d426aa-e043-4de7-be53-6c9b7ea84e94)
![IMG_1582](https://github.com/raivo-otp/ios-application/assets/88580809/d7febf1a-ccb6-486a-bd51-5755bcac9bf5)
![IMG_1583](https://github.com/raivo-otp/ios-application/assets/88580809/6d75abd2-fb40-457b-bdbc-20eaafe119fe)

**Comment by tijme** [comment]
Hello @jmrsn,

The Mobime team will work on Raivo and keep it up to date. More information will follow soon!

**Comment by Ardakilic** [comment]
They didn't work on and keep this up-to-date as we see, actually they did literally nothing since the copyright change:

https://github.com/raivo-otp/ios-application/commits/master
https://github.com/raivo-otp/macos-receiver/commits/master

Time to move on!
