### ISSUE TITLE
Hide searchbox at top of homepage

### ISSUE THREAD

**Issue by f2sky** [raivo-otp/ios-application#29]
The searchbox at the top is not shown by default, only when I slide the screen or click the search button at the bottom.

**Comment by tijme** [comment]
@f2sky Wow, this took me a while to look into... Excuse me for that.

What exactly do you mean by this feature request? I see the (search)bar at the top of the homepage by default. Do you want this or not? And if not, what would you prefer as a solution? There should be a bar at the top anyway, since there is also the add/plus button.

**Comment by f2sky** [comment]
Raivo otp is one of the best interface design APP I've ever used, I just want a cleaner interface for this suggestion. Indeed the search box at the top along with the add (scan) button would not look lonely (hahahahaha).Maybe show the APP name at the top - Raivo otp, just like Microsoft Authenticator? (This is just a suggestion for interface optimization.)

**Comment by tijme** [comment]
Hey @f2sky, would you mind sending me a screenshot of your homepage in Raivo? You can blur the tokens if you'd like. I'm just curious to see what your homepage of Raivo looks like.d

**Comment by f2sky** [comment]
Same screenshot as the one you submitted in the AppStore, with a search box at the top and a search button at the bottom.

In terms of UI design, the functions are duplicated and the search box at the top is not very aesthetically pleasing to display all the time.For example, you can design it in such a way that the search box at the top is displayed only when you slide down the screen or click the search button at the bottom.Of course, there are other design options available.

This is not a bug, just a design optimization suggestion.After all, Raivo OTP is a well-designed APP that I really like.

**Comment by tijme** [comment]
Ah, now I understand. I figured you meant "The searchbox at the top is not shown by default", as a statement, instead of as the feature request.

I'll think about this improvement. Thanks!

**Comment by tijme** [comment]
Merging this with #94
