### ISSUE TITLE
Show sync status in settings

### ISSUE THREAD

**Issue by f2sky** [raivo-otp/ios-application#30]
Show sync status in settings, such as time, iCloud account, etc.

**Comment by tijme** [comment]
This will be released in TestFlight version 1.1.17 soon. After the testing phase it will be released as public release.

https://github.com/raivo-otp/ios-application/releases/tag/build-36

Here are some screenshots of the upcoming syncing status; 

**Settings (nothing left to sync):**
![main-screen-synced](https://user-images.githubusercontent.com/5873573/121246781-cb3d1580-c8a1-11eb-877c-e5348ad76458.png)

**Edit OTP (could not be saved):**
![edit-screen](https://user-images.githubusercontent.com/5873573/121246791-cc6e4280-c8a1-11eb-9d8a-f200fe4c88ce.png)

**OTP list (1 unsynced OTP):**
![main-screen](https://user-images.githubusercontent.com/5873573/121246793-cc6e4280-c8a1-11eb-800c-24050fbb765a.png)

**Settings (2 unsynced OTPs):**
![settings-screen](https://user-images.githubusercontent.com/5873573/121246795-cd06d900-c8a1-11eb-9962-d83544b3e449.png)
