### ISSUE TITLE
App does not work after update

### ISSUE THREAD

**Issue by ernie57** [raivo-otp/ios-application#320]
Hi - I installed the update today and now the app does not work and only crashes. I have removed and reinstalled it a few times and that didn’t fix the issue. Please help. Thanks.

**Comment by phitsc** [comment]
I have the exact same problem. Also, the app title reads "Raivo Debug"

**Comment by ernie57** [comment]
yes!

**Comment by TheRealDanini** [comment]
same problem, lost all of my keys because of this. does anyone know how to force rollback an app update so I can pull my keys out of this pos to use in another app?

**Comment by Flysim97** [comment]
I have the same problem
