### ISSUE TITLE
Guys, do you have open source 2FA app alternatives that protect our privacy and have active support?

### ISSUE THREAD

**Issue by Joberbaro** [raivo-otp/ios-application#353]
Chicos, ¿tienen alternativas de aplicaciones 2FA de código abierto que protejan nuestra privacidad y tengan soporte activo?

**Comment by Roadmaster** [comment]
Ente https://ente.io/blog/auth/

**Comment by slimequeen3251** [comment]
This is also: https://bitwarden.com/help/bitwarden-authenticator/

It's Bitwarden. But again, can change at anytime. Be sure you have backups ready.

**Comment by Tmp341** [comment]
If you have iOS 16.4+, try [2FAS](https://apps.apple.com/us/app/2fa-authenticator-2fas/id1217793794) or [Ente Auth](https://apps.apple.com/us/app/ente-auth/id6444121398).
If you have iOS below 16.4, [Ente Auth](https://apps.apple.com/us/app/ente-auth/id6444121398).

**Comment by lbsekr** [comment]
> Ente https://ente.io/blog/auth/

It is also relatively easy to host yourself. If you are into that

**Comment by Joberbaro** [comment]
Excellent guys, thank you for such a valuable contribution. We need an open source app. That they do not bow to governments and allow us to have a security and privacy of the latest level, thank you, everyone is very valuable contributions, it is important to have alternative dispersants

**Comment by Ardakilic** [comment]
Ente is nice. If you want it, you can use without any kind of sync and get local encrypted backups.

**Comment by Scorpoon** [comment]
Aegis would also be an alternative, local encrypted backups and open source:
https://github.com/beemdevelopment/Aegis

**Comment by jgsource** [comment]
@Roadmaster Ente won't even let me import my raivo codes. It says could not parse file when i try to import my json. Is this a bug with ente?

**Comment by bbb651** [comment]
> Aegis could also be an alternative, local encrypted backups and open source: https://github.com/beemdevelopment/Aegis

It's android only 🤦

**Comment by Scorpoon** [comment]
> > Aegis could also be an alternative, local encrypted backups and open source: https://github.com/beemdevelopment/Aegis
> 
> It's android only 🤦

Oh sry, my fault. I just found a post on reddit about the raivo issues and read a bit through them here on github and didn't notice that it's an apple only app.

**Comment by elliotwutingfeng** [comment]
2FAS on iOS also supports imports from Raivo, https://github.com/twofas/2fas-ios

**Comment by Tmp341** [comment]
> @Roadmaster Ente won't even let me import my raivo codes. It says could not parse file when i try to import my json. Is this a bug with ente?

Are you showing ZIP file or JSON file?
