### ISSUE TITLE
Everything lost ??!

### ISSUE THREAD

**Issue by Turniket23** [raivo-otp/ios-application#356]
hello, just now I opened raivo after few updates and I was logged out and it seems I lost every key ???!! This cant be real man please chill me out, there was so much of that… everything I’ve found so far was some type of token in my bitwarden note so I think I can synchronize it using that token ?? Where can I use it please ? Im using latest iOS na iPhone 12 mini

**Comment by mobime-org** [comment]
Hello there,
There is a pending version at the app store just waiting for approval to get this sorted out.

Thank you for your patience.
