### ISSUE TITLE
All of my MFA tokens have disappeared (WHAT THE FUCK!?)

### ISSUE THREAD

**Issue by TehBrian** [raivo-otp/ios-application#359]
My open letter to Mobime is at the bottom of this bug report.

**Describe the bug**
When I open the app, my MFA tokens are not there.

**To Reproduce**
1. Today, my Raivo app turns into "Raivo Debug," which crashes upon open.
2. Update the Raivo app in the App Store in hopes of fixing the crash.
3. The app is completely modified (NOT based on any source code in this repository), with the "feature" of importing/exporting token archives now being locked behind a $10 paywall.
4. My MFA tokens are gone.

**Expected behavior**
My MFA tokens are there.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - Version: 101

**Additional context**
Are you fucking kidding me? How the hell can you push an update that deletes all of your users' sensitive information and then have the audacity to prevent them from importing their archived tokens unless they pay a $10 fee? This is essentially ransomware. I pray that my archive is in a non-proprietary (ideally text) format else I will have lost _all_ of my 2FA authentication tokens.

I have never used profanity on this website because I never thought that I'd need to, and I really hope that I'm not coming across as anything more than overtly frustrated—I in no way mean to insult, harass, or otherwise demean individuals—but what the **actual fuck**. How the **FUCK** can you take an app initially built from open source  code, modify it to hell, and then push an update to the app containing private code that resets users' data and introduces in-app purchases with absolutely no heads up? Really?

I didn't migrate from Raivo 10 months ago when Mobime acquired the app because I thought that, if god forbid any stupid changes like these arose, they'd have the decency to let me know in advance. What a stupid cunt I was.

Like, what the hell. Seriously. Revert this shit.

Respectfully,
Brian

**Comment by bbb651** [comment]
Yeah this sucks :/ 

Please make sure to 1-star review, report on the App Store and report @tijme on github hopefully we can get them banned.

**Comment by mobime-org** [comment]
Hello Brian,

Have you tried the latest version 101? We will be releasing a new update to the app store in the next few hours, including the import and export feature.

Please contact us at contact@mobime.org so that we can provide you with personalized assistance in the future.

Kind regards,
