### ISSUE TITLE
🤬 WTF?!?! Moving on Alternatives

### ISSUE THREAD

**Issue by kenjikato** [raivo-otp/ios-application#364]
All of my keys are GONE!!! WTF?!?! 🤬

So what do people think?

1. [2FAS](https://2fas.com/browser-extension/)
or
2. [Ente Auth](https://ente.io/auth/)

Both let you import a backup from Raivo if you have one.

**Comment by Tmp341** [comment]
2FAS required above iOS 16.4 so i only had Ente Auth as an open source option.
