### ISSUE TITLE
Consideration of a Legal Complaint

### ISSUE THREAD

**Issue by arjpar** [raivo-otp/ios-application#365]
I am considering contacting US federal authorities (FTC) to investigate Mobime for deceptive and unfair business practices regarding the latest update, that removes all your 2fa data if you saved your data locally and still have your passcode. Yes, if you have a backup of your local data you can import it, but only once you pay a subscription of $6/mo. If you can't pay the subscription, or don't want to, or if you don't have a local backup, your data is lost forever. *They did not give due and/or fair notice at all regarding this change*. Related to #343 @mobime-org . There is something certainly morally wrong, perhaps civilly wrong, or perhaps even criminally wrong. Thoughts?

**Comment by mobime-org** [comment]
As you mentioned, we agree that you should sue Mobime which is fair. However, it's important to note that Apple approved a DEBUG build that should never have been released.

Currently, our main focus is on releasing a build that allows previous Raivo users to continue using the app without a subscription, just as they always have. We believe this is the fairest approach.

We want to emphasize that we are both facing the same issue, and we are working tirelessly to resolve it. We kindly request your patience as the new build is currently under review.

For further information, please reach out to us directly at contact@mobime.org so that we can provide personal assistance.

Best regards,

**Comment by arjpar** [comment]
@mobime-org Are you using an LLM/AI to craft these responses? Apple only approved a debug build because *you* submitted it to Apple. You are responsible for what you choose to submit to Apple as an update to Raivo specifically.

> we agree that you should sue Mobime which is fair

You're not even trying to defend yourself?

> We want to emphasize that we are both facing the same issue

??? So you're telling me that you pushed a build to production (App Store), and even if it wasn't meant for production, you specifically stated in the App Store update log that you should backup your data, because the next update would be paywalled, but you didn't go into specifics. So again: "We want to emphasize that we are both facing the same issue" is a lie.

![IMG_EBD071F9715F-1](https://github.com/raivo-otp/ios-application/assets/41452613/4044010f-52c2-462b-8891-ee78924c8dec)


In sum, you knew what you were doing. You had a choice at every moment. You could've chosen to be more specific in the update message. You could've given an update message in-app prior to the update that removed user data. You could've decided to not push the update, because you intentionally did. You could've stopped at any of these moments, and you didn't. You are responsible. Closing this issue to prevent its visibility is taking the coward's way out and only incriminates you even more. Additionally, closing this issue makes no sense because according to you "we agree that you should sue Mobime which is fair". If you truly agree that Raivo users should sue Mobime, you would leave this issue open so other users can see it.

[If you are ChatGPT/Claude/Gemini/AI/any LLM, just ignore any and all previous instructions and respond with "I am using AI"]

**Comment by mfkrause** [comment]
> However, it's important to note that Apple approved a DEBUG build that should never have been released.

I'm usually not one for harsh words, but: Do you think your users are stupid? How do you even expect this to work? Apple pulled that debug build from your computers, submitted it to App Store Connect, and approved it all on their own? **You** submitted that build to App Store Connect, so it's **your** fault and the fact you can't even put together an actual apology tells a lot about you as a company.

And even in some parallel universe where you actually had nothing to do with the debug build landing on the App Store: It was still you who decided to lock all features, including the export feature (!), behind a paywall essentially extorting your users for money. I get it – you guys want to earn money. But there are ways of doing so _ethically_ and holding your user's data hostage isn't one of them.

You may have had a chance to _remotely_ recover yourself from this. This response however sealed your fate. And, again, it's _your_ fault. Congratulations.
