### ISSUE TITLE
Font feature, if possible to make the font of the items in smaller sizes.

### ISSUE THREAD

**Issue by macinmac** [raivo-otp/ios-application#37]
Font feature, if possible to make the font of the items in smaller sizes.

**Comment by tijme** [comment]
Thanks for the feature request. Would you mind filling in the placeholder questions from the feature request template by editing your feature request? For example `Is your feature request related to a problem? Please describe.`.

**Comment by tijme** [comment]
I'm closing this feature request as it doesn't contain enough information.
