### ISSUE TITLE
Option to hide/show icons? Thanks you.

### ISSUE THREAD

**Issue by macinmac** [raivo-otp/ios-application#38]
Option to hide/show icons? Thank you.

**Comment by tijme** [comment]
Thanks for the feature request. Would you mind filling in the placeholder questions from the feature request template by editing your feature request? For example `Is your feature request related to a problem? Please describe.`.

**Comment by tijme** [comment]
Closed as inactive and another more extensive issue exists; https://github.com/raivo-otp/ios-application/issues/56
