### ISSUE TITLE
Synchronization is currently disabled

### ISSUE THREAD

**Issue by brryantt** [raivo-otp/ios-application#39]
I would like to sync Raivo with my iCloud, however I am unable to do so. In settings, it says "Synchronization is currently disabled" with both Account and Provider saying "offline".

**Comment by tijme** [comment]
Hi @brryantt,

Currently this is not supported in Raivo. A feature request has been made in #33. However, you can migrate to iCloud manually. 

1. Make an export of your OTP's in the settings screen.
2. Verify you can open your export correctly, and that all OTP's are in it.
3. Sign out of Raivo in the settings screen.
4. Sign in again, and choose iCloud Sync during the setup.
5. Scan all QR-codes from your exported archive.
