### ISSUE TITLE
TOTP codes are visible on app switcher

### ISSUE THREAD

**Issue by EspadaV8** [raivo-otp/ios-application#42]
**Is your feature request related to a problem? Please describe.**
When switching between apps the list of 2FA codes should not be visible. 

**Describe the solution you'd like**
Similar to all banking apps or password manages, when switching apps the screen should be blanked so that the 2FA codes can’t be seen. 

**Describe alternatives you've considered**

**Additional context**

**Comment by EspadaV8** [comment]
![9F303D75-D695-4720-8667-7B015658045B](https://user-images.githubusercontent.com/115825/115115292-01af9000-9fd7-11eb-8a5b-79cece8cff4c.jpeg)

These are the codes that should be hidden

**Comment by tijme** [comment]
Hi @EspadaV8,

Could you provide some more details on why you would want them to be hidden? 

You will only see the tokens if you've unlocked the app a few minutes before switching, so I am not seeing a security risk just yet.

Thanks,
Tijme

**Comment by EspadaV8** [comment]
I was originally thinking security (it would still be nice for this), however, after using the app for a couple of weeks now I think it would help a lot when you have a number of TOTP added. Typing in a code from the app into my computer and looking away and back always takes a second or 2 to find the one I'm after again because it's just this long list of numbers  all trying to grab my attention with their red colour highlight. Having to tap to reveal would mean the screen is a lot less busy and instantly give my eyes something to lock on to when looking back.

**Comment by filmoreast** [comment]
That’s not true.  The codes are visible in the switcher once the app is opened and unlocked, and they remain visible (even after the lock out period).  Also, when the app is opened (and it spins around before authentication), the codes are visible (then the authentication screen appears).

**Comment by LawHoo** [comment]
One security risk is that someone could see the list of accounts after the Inactivity Lock period, and sometimes the names of the accounts themselves are sensitive. This is a screenshot showing the difference between Raivo OTP and the OTP Auth app.
![IMG_2355 - Copy](https://user-images.githubusercontent.com/21247076/185242252-45be28dd-b965-4d2d-b50a-125ad9bfbec7.PNG)

**Comment by tijme** [comment]
Will be fixed in the next release 🚀
