### ISSUE TITLE
Screen cutoff

### ISSUE THREAD

**Issue by sanityvoid31** [raivo-otp/ios-application#43]
**Describe the bug**
Opening the app, the backup option is cutoff and you cannot scroll to see more.
EDIT: Found out it is how the font size in iPhone works, so maybe the dynamic sizing of the font or app isn't set right. Smaller font size makes it fit better.

**To Reproduce**
1. Open App for first time, welcome screen
2. Click on Continue
3. Screen is cutoff on storage providers
4. See screenshot

**Expected behavior**
Should be able to see what is available or not.

**Screenshots**
![IMG_5840](https://user-images.githubusercontent.com/64928134/115611412-92d57e00-a2d9-11eb-92fa-9a115482819b.PNG)

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: iOS
 - Version 14.4.2

**Additional context**

**Comment by tijme** [comment]
Hi @sanityvoid31,

Thank you for reporting this. I can confirm it is indeed a bug and it shouldn't happen. I will implement a fix when I have the time. This can take a while though.

**Comment by tijme** [comment]
Fixed in commit https://github.com/raivo-otp/ios-application/commit/4a0f6ac0356694f4eca59c1042f52b9c7504b743. Will be pushed to public App Store within a few weeks, after beta testing.
