### ISSUE TITLE
Export json has more entries then the export html.

### ISSUE THREAD

**Issue by zoredache** [raivo-otp/ios-application#45]
**Describe the bug**

Was evaluating Raivo OTP. I added a bunch of fake entries, deleted a bunch and later tried an export. The `raivo-otp-export.html` seems to have the current list of accounts that I see in the app interface. The `raivo-otp-export.json` seems to also include the entries I had deleted.

**To Reproduce**

- Start the app from a blank state, no synchronization.
- Add some entries, delete some
- Export the zip and email to yourself.
- Examine the files in the export ZIP .

**Expected behavior**

I am not entirely sure what to expect here, since I am a new to this application and evaluating it.. Having the deleted entries in the JSON could be potentially useful to people, though it might be more useful if the JSON included a field mentioning that the entry was deleted and when.

I included the contents of an export files here.

- https://gist.github.com/zoredache/4f645cd2050295ed0c0be7906775f8d9

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2nd Gen
 - OS: 14.5.1

**Conclusion**

Anyway I am not sure if this is a bug or what you would want to change here. Just adding this issue since the results were not what I would have expected.

**Comment by tijme** [comment]
Thanks for the clear bug report @zoredache. I will fix this when I have the time (might take a while).

**Comment by tijme** [comment]
This will be released in TestFlight version 1.1.15 soon. After the testing phase it will be released as public release.
