### ISSUE TITLE
Stuck at loading Storage providers

### ISSUE THREAD

**Issue by ZhenWang7** [raivo-otp/ios-application#46]
**Describe the bug**
The storage provider page would not finish loading.

**To Reproduce**
1. Open the App
2. Click on continue
3. See error

**Expected behavior**
The app will finish loading 

**Screenshots**
![303D9FC7-C43E-4667-97B0-BCED560F808C](https://user-images.githubusercontent.com/54323667/119736931-7da9bd00-be4c-11eb-9a97-07657cc4fb27.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Version 14.6

**Additional context**

**Comment by tijme** [comment]
Hi @ZhenWang7,

I think I need some more info to reproduce this problem. Did you have internet? Was your DNS working? Some causes that I can think of relate to your internet connection, as the selection state changes from disabled to enabled after the iCloud info is retrieved from Apple.

Could you try it again? Maybe reinstall the app first.

Thanks!

**Comment by ZhenWang7** [comment]
Hi @tijme ,

I had internet and the DNS was working. 

It appears to be something wrong with the network settings on my iPhone. The following steps fixed my issue. 

Settings -> General -> Reset -> Reset Network Settings. 

Thank you for your help!

**Comment by tijme** [comment]
Great to hear, enjoy Raivo ;)
