### ISSUE TITLE
App Icon alternatives

### ISSUE THREAD

**Issue by mtloz** [raivo-otp/ios-application#47]
It would be _nice to have_ a few more app icon alternatives, much preferably with smaller icon / larger margin.

![Raivo Icons](https://user-images.githubusercontent.com/2070048/120940747-cd11a800-c6ec-11eb-9b13-0a14fcc41ecb.png)

**Comment by tijme** [comment]
Wow, nice icons @mtloz! Would love to implement this in the future. So would you like a screen in settings where you can choose the app icon ore something?

Anyhow, I'm not sure when I have the time to implement this. So it might take a while for me to finish this.

**Comment by 1lgatto** [comment]
> It would be _nice to have_ a few more app icon alternatives, much preferably with smaller icon / larger margin.
> 
> ![Raivo Icons](https://user-images.githubusercontent.com/2070048/120940747-cd11a800-c6ec-11eb-9b13-0a14fcc41ecb.png)

I would like this too!

**Comment by tijme** [comment]
@mtloz Within the Assets folder of this repo there is a PSD file of the logo (https://github.com/raivo-otp/ios-application/blob/master/Assets/app-icon.psd). Is this something you used to design these new logo's? And if so, would you mind sharing the resulting PSD's with me? 😄

**Comment by tijme** [comment]
@1lgatto hey, did you have any chance to look at the PSD? I just pushed the change which allows you change the app icon, this will probably go the testflight soon, but I don't really have any alternative icons right now.

https://github.com/raivo-otp/ios-application/commit/e98c6d8c228403c029335f14c2600ac9f7507f82

**Comment by 1lgatto** [comment]
>  hey, did you have any chance to look at the PSD?

> 
Unfortunately no.

**Comment by tijme** [comment]
@mtloz would you like to put some efforts in creating alternative icons using the provided PSD?

**Comment by tijme** [comment]
Implemented in the latest version.
