### ISSUE TITLE
I can't see the icons

### ISSUE THREAD

**Issue by JuanPerezPerez1** [raivo-otp/ios-application#53]
The icons are not shown and when I try to put them it tells me that
” Refreshing failed icons. It An SSL error has occurred and a secure connection to the server cannot be made”

**Comment by tijme** [comment]
Will fix this in two weeks. The SSL cert expired somehow. But I'm currently on holiday so can't fix it.

**Comment by tijme** [comment]
Fixed by renewing the TLS certificate.
