### ISSUE TITLE
Icons import issue

### ISSUE THREAD

**Issue by ilyak83** [raivo-otp/ios-application#54]
**Describe the bug**
Unable import icon from Raivo OPT repository.

**Screenshots**
![image](https://user-images.githubusercontent.com/37582972/128392029-69315ae1-1d1b-44eb-a95d-a035ee02f2a7.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS14]
 - Version [e.g. 7.1]

**Comment by tijme** [comment]
Will be fixed next week. See #53.
