### ISSUE TITLE
Inactivity timeout causes fingerprint popup on Mac OS

### ISSUE THREAD

**Issue by wedgeV** [raivo-otp/ios-application#57]
**Describe the bug**
I'm running Raivo on my M1 Mac, and the inactivity timeout makes it pop up a fingerprint scan dialog while I'm working in other apps.

**To Reproduce**
1. Install Raivo on Mac
2. Run it and unlock, set inactivity timeout to 20secs
3. Go back to password page
4. Switch to a different app and keep Raivo running in the background
5. After 20secs a fingerprint unlock overlay dialog will pop up (that has to be either dismissed or authenticated)

**Expected behavior**
Raivo should just lock itself in the background and not interrupt the user, and only ask for fingerprint when the user switches back to Raivo. (Maybe also add an option to disable inactivity timeout?)

**Smartphone (please complete the following information):**
 - Device: Macbook Pro M1
 - OS: MacOS
 - Version: 11.5.2

**Additional context**
I guess Mac OS is not really officially supported, but it actually works 100% fine (as far as i can tell) except for this issue. Also noticed in the code that only touch events are used to reset the inactivity timer, not sure of clicks on MacOS are counted as "touch".

**Comment by tijme** [comment]
Hey @wedgeV,

Thanks for the very extensive bug report. Pretty cool that you're running Raivo on your Mac! Didn't even know this was possible! Raivo OTP for MacOS isn't officially supported. Instead, I'm working on [a separate MacOS app](https://github.com/raivo-otp/macos-receiver) which will be released soon. Therefore, I'm leaving the bug report for now. I hope you understand.

Thanks,
Tijme

**Comment by tijme** [comment]
The separate MacOS app is out. I'll mark this as Wontfix for now, but I'll leave it open.

**Comment by brycewray** [comment]
@tijme is the separate macOS app required for copy/paste from the iOS app because Apple's Universal Clipboard is considered insecure? TIA for the info.

**Comment by tijme** [comment]
Universal Clipboard should work too (not sure if it's secure). Main advantage of the MacOS receiver is that it can be used cross iCloud account and without Bluetooth.

**Comment by tijme** [comment]
Decided to close this as it's a wontfix that is still open. As stated, there is a native MacOS companion app now.
