### ISSUE TITLE
Sync to Nextcloud

### ISSUE THREAD

**Issue by killerb77** [raivo-otp/ios-application#58]
**Describe the solution you'd like**
Currently can only sync to iCloud.  Would be nice to be able to sync to Nextcloud.

**Comment by beerisgood** [comment]
This would only increase your attack surface.
Nextcloud is also awfully bad for everything.

Anyway, you can save your database locally and then sync it to and with what you like.

**Comment by tijme** [comment]
I hope to add other synchronisation providers in the future. Not specifically Nextcloud, but just other protocols that can be used for various providers.

However, it might take a while as it doesn't have the top priority for now. I first have to implement other feature requests.

**Comment by christopher87** [comment]
Hi,

Synchronisation with a WebDAV server would be awesome :)

Thanks for your work !

**Comment by tijme** [comment]
Tracked in #49. Therefore closing this.
