### ISSUE TITLE
"Sign out of Raivo" does not reset iOS share sheet favourites

### ISSUE THREAD

**Issue by bluto32** [raivo-otp/ios-application#60]
**Describe the bug**
It appears to be impossible to completely restore Raivo's default settings, in particular the "Edit Actions..." settings after "Export OTPs to ZIP archive".

**To Reproduce**
1. Click on "Settings"
2. Click on "Export OTPs to ZIP archive"
3. Click on "Export"
4. Click on "Edit Actions..."
5. Change the settings to anything other than default.
6. Click "Done" and go back to the main settings page.
7. Click "Sign out of Raivo" and confirm.
8. When repeating steps 1 to 4, the "Edit Actions..." settings have not reverted back to their defaults.

**Expected behavior**
"Sign out of Raivo" ought to reset _all_ settings back to default values. It appears to revert the other settings back to defaults (such as "Inactivity lock"), just not the "Edit Actions..." settings.

Note: I also tried deleting the Raivo app from within iOS and the reinstalling it. Surprisingly, this didn't reset anything other than the master password.

**Smartphone**
iPhone 7
iOS 14.7.1 (up to date)

_P.S. As with my other bug notice, apologies if you also get it on Raivo Freshdesk which I have found to be problematic. And thank you for writing such a beautful app: Raivo is by far my favourite 2FA app for iOS :-)_

**Comment by tijme** [comment]
Hi @bluto32,

Can you maybe screenshot which settings you mean? Based on the steps you provided it looks to me like this is iOS behaviour, and not specifically Raivo OTP behaviour. I'm not sure if I'm able to erase those settings.

**Comment by bluto32** [comment]
Thanks for your note; I have attached a photo here for you.

From memory, the default settings had "Copy" as the only favourite, with both "Save to Files" and "Add Tags" underneath but visible. My current settings (as on the photo) have "Save to Files" as the only favourite, "Copy" as visible underneath (it is always visible in your app as it has no slider) and "Add to Tags" as invisible.

If these are iOS settings, they aren't erased when uninstalling the app (or when clearing iCloud backup of Raivo files).

!['Edit Actions ' settings](https://user-images.githubusercontent.com/90004890/132040659-abace696-673b-4b5c-800b-436f5960914d.png)

**Comment by tijme** [comment]
@bluto32 Thanks for reporting this. I've marked this as Wontfix for now as these favourites are stored outside of Raivo OTP, in iOS instead of in the app.

**Comment by bluto32** [comment]
Understood - thank you for clarifying.

**Comment by tijme** [comment]
Closing this so it won't show up in the open issues, as it's a wontfix.
