### ISSUE TITLE
Remove Face ID option when opening the app.

### ISSUE THREAD

**Issue by shane-anderson** [raivo-otp/ios-application#62]
**Is your feature request related to a problem? Please describe.**
no problem. just suggestion 

**Describe the solution you'd like**
Currently when you open the app it will propmt you to scan your face with Face ID. since we are already in our phones can we have this disabled? OR have an option within the settings to remove the app lock altogether. if I disable Face ID it will then require me to input a password. I dont want to do either of those since I'm already in my iPhone..

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by tijme** [comment]
Hi @shane-anderson,

Currently Raivo OTP is designed in such a way that it always needs a master password. This master password is stored in Secure Enclave, which can be accessed upon FaceID/TouchID or passcode. I don't want to remove this security feature from the app as it would lower the boundary for malicious users.

I hope you don't mind the FaceID unlock too much. I tried to make it as user friendly as possible.
