### ISSUE TITLE
What's the difference between the red and grey one-time password (OTP)?

### ISSUE THREAD

**Issue by Tealk** [raivo-otp/ios-application#63]
Hello,

Thanks for the great app. I'm just wondering what the gray number means.

**Comment by tijme** [comment]
Hi @Tealk,

Let's call the number a one-time-password (OTP). The red OTP is the current, active OTP. This can be used for signing in. The grey OTP is the previous one. It may seem weird to show the previous OTP, but it's actually also still valid to use while signing in.

Whenever you're typing the OTP in your browser, and it expires in the meanwhile, you can continue typing in the OTP as it moved from red to grey and you can still see it in the app.

**Comment by Tealk** [comment]
Asso, I first thought this was the upcoming OTP and checked that a few times too. But I never did the check the other way around.

Thanks for the information.
