### ISSUE TITLE
No option to unlock using fingerprint or phone PIN

### ISSUE THREAD

**Issue by svend** [raivo-otp/ios-application#65]
**Describe the bug**

I used to see and options to use the phone PIN or fingerprint to open the application. Now the only option is the application passcode. I have been using fingerprint or phone PIN to open the application previously.

I noticed this after updating to iOS 15.0.

**To Reproduce**

1. Close Ravio OTP
2. Open Ravio OTP

**Expected behavior**

Options to use phone PIN or fingerprint to open app.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2
 - OS: iOS 15.0
 - Version 1.2.2

**Comment by tijme** [comment]
Hi @svend,

This should be working. Can you check if it's currently enabled in settings?

**Comment by tijme** [comment]
If it is enabled, could you make a screen capture?

**Comment by svend** [comment]
Hi @tijme 

Here are screenshots of the application. I don't see any option in the settings to enable biometric unlock.

![image](https://user-images.githubusercontent.com/306190/135319352-b1cbb1fa-8728-4001-af8c-d701761f1ee9.png)

![image](https://user-images.githubusercontent.com/306190/135319301-618c2a30-d66e-4cde-9426-ac5703b7132a.png)

**Comment by svend** [comment]
> Thanks for the screens. Can you first sign in using the passcode, and then check the settings? You'll see more options, such as the TouchID/FaceID option. Can you check if it's enabled?

I haven't been able to remember or find the application passcode I set. I was using biometric authentication or my phone's PIN to unlock the application.

**Comment by tijme** [comment]
Hi @svend,

Unfortunately I can't help if you forgot the passcode, as all OTP's are encrypted using the passcode + master password. If you had iCloud sync enabled in the app, you're lucky. In that case you can just sign out, and sign-in again. You can then set a new passcode, and get into the app again. However, you do need your master password for that. If you forgot that too, then there is no way to recover.
