### ISSUE TITLE
How to decompress exported zip files locally

### ISSUE THREAD

**Issue by f2sky** [raivo-otp/ios-application#66]
Before exporting the backup file locally, I changed the password within the app - to make sure I wouldn't forget it, but after exporting, I couldn't unzip it under macOS with the recommended **the unarchiver** tool, always prompting for a password error. But now that I've flashed my phone and reinstalled Raivo OTP, I can't import the local backup either. And when I open the iCloud backup, it also always prompts password error. Is there any way for me to retrieve the saved authentication code?

In my previous proposal, I suggested to provide the method of **exporting backup files without encryption**, which is suitable for use to scenarios such as swapping and flashing phone. Users choose their own easy way to handle their data, there is no need to force a complex or even potentially irreparable loss. I wonder if it can be adopted?

The most important thing right now is how do I save my data?

**Comment by tijme** [comment]
Did you use your password or passcode to decrypt the ZIP? These are two different things in Raivo. The passcode is the 6 digit code to unlock the app. The password is something you entered while setting up Raivo.

You should use the password for decryption.

**Comment by tijme** [comment]
Please reopen when you specify more info.
