### ISSUE TITLE
Field for Recovery Codes

### ISSUE THREAD

**Issue by iksvd** [raivo-otp/ios-application#68]
I’d very much like a field where I can add the recovery codes for the 2FA accounts. Maybe when you go to Edit there could be an extra field just for that. Or maybe an entire section in the starting menu. Just some place where when the password for some strange reason doesn’t work I can go to and see my recovery codes and pass phrases.

Thank You for your work!

**Comment by tijme** [comment]
Hmm, but adding these recovery codes would defeat the purpose of two-factor authentication right? As the one-time password and password/recovery code are stored in the same location.

**Comment by PathfinderKP** [comment]
What if it would be called a note field?
Like the ones we have in the Reminder app or the Calendar app and anyone can write extra information there.

**Comment by tijme** [comment]
I decided not to implement this as I feel most OTP's don't need codes. And adding backup codes to an OTP account defeats the purposes of multi-factor authentication. Those restore codes should be stored offline.
