### ISSUE TITLE
Save icon set at local storage instead of retrieving every launch

### ISSUE THREAD

**Issue by hiangeel** [raivo-otp/ios-application#72]
I see that every time the app launch, it calls to `https://raw.finnwea.com/raivo-issuer-icons/dist/` (`iconsURL` variable in `AppHelper.swift`) to get the icons of passwords.
That make the app look like getting lag because all icons take a little moment to refresh. I don't know why you have to do that? Why don't you save icons at local storage?

**Comment by tijme** [comment]
Please reopen when you supply more info.
