### ISSUE TITLE
"Search" reverses the Username order of tokens with the same Title

### ISSUE THREAD

**Issue by bluto32** [raivo-otp/ios-application#76]
**Describe the bug**
If two or more tokens have the **same** "Title (issuer)" field, but different a "Username" field, then:
When starting Raivo, the tokens appear in the expected order: they are ordered alphabetically by Title, and then by Username.
However, if the "Search" button is pressed, as soon as the next button is pressed (whether it is a letter or "Cancel"), the tokens are reordered as follows: alphabetically by Title, and then **in reverse** by Username. This persists until Raivo is closed and restarted.
I first noticed this with my Kraken tokens which have the same Title ("kraken.com") but different Usernames ("Kraken - Funding" and "Kraken - Sign-in"). A little experimentation with other tokens shows it to be a consistent bug, albeit a minor one.

**To Reproduce**
1. Add any two tokens.
2. Edit them so so they have the same Title but different Usernames.
3. Press "Search" and then press anything else.
4. The above tokens now appear in reverse order alphabetically.
5. Close Raivo and restart: the icons are back in the correct order.

**Expected behavior**
The ordering should not change after pressing "Search".

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS14.8.1

**Comment by tijme** [comment]
Thanks for reporting @bluto32, will look into this in a future release and make sure to fix it.

**Comment by tijme** [comment]
Unfortunately I can't reproduce your issue. Do you have any more details? 

![IMG_3685](https://user-images.githubusercontent.com/5873573/150678893-b0feb0bd-f5fd-481b-a2ba-3c4deb0120d2.jpg)

![IMG_3686](https://user-images.githubusercontent.com/5873573/150678890-713c5692-43e8-41f0-962f-9b7e07c892e0.jpg)

**Comment by tijme** [comment]
This might be the fix: https://github.com/raivo-otp/ios-application/commit/d042912cde35ea065d26513ce678bb361cc310c2. Will be pushed as public release soon.

**Comment by bluto32** [comment]
Thanks for looking into it and getting back to me. I've experimented a bit more, and have discovered another reason behind the order reversal. Raivo seems to remember the order in which these tokens (with the same "title" but different "usernames") are added. If they are added in reverse alphabetical order, then the problem reveals itself when searching. Otherwise, Raivo behaves fine. In your example, try editing the top username so it says "Testing" at the end instead of "Funding". I think they will appear in the correct order initially, but swap when trying to search.
