### ISSUE TITLE
Invalid token on Bitwarden

### ISSUE THREAD

**Issue by Stooovie** [raivo-otp/ios-application#77]
**Describe the bug**
Bitwarden OTP is always wrong, despite successfuly created by a QR code

**To Reproduce**
try to login to Bitwarden
copy OTP from Raivo
paste into Bitwarden

**Expected behavior**
I expect to be able to log in
 
**Screenshots**

**Smartphone (please complete the following information):**
iPhone 11 Pro, iOS 15.1, Raivo 1.3.0

**Additional context**
Bitwarden was added into Raivo by scanning a QR code, so there's probably not really a space for user error

**Comment by Stooovie** [comment]
I was able to get into BW with the recovery code, delete the OTP auth method, re-add it and not it works, but it did not work before this procedure.

**Comment by tijme** [comment]
Do you have any more information to reproduce the issue? I'm not able to reproduce it at the moment.

**Comment by Stooovie** [comment]
Hello, I don't, sadly. I don't know what it was but the codes didn't work at all, and I had to use the emergency code to get into BW. A new 2FA code made for BW works as expected. What I find weird is that the original (not working) code passed the test that is required to turn 2FA on at all.

The case is closed though as I don't have any more details. Thanks for your time.
