### ISSUE TITLE
Personal iCloud grayed out

### ISSUE THREAD

**Issue by dokterkats** [raivo-otp/ios-application#78]
**Describe the bug**
I was using Raivo while it was connected to my iCloud account. But after opening the app recently I was automatically logged out and now the personal iCloud option is grayed out.

**To Reproduce**
My iCloud storage was full, that might have caused it. After freeing up space it’s still grayed out though 

**Expected behavior**
being able to login using my iCloud account

**Screenshots**
![2A6E8E26-B58F-459A-AAC3-660A86D74C5F](https://user-images.githubusercontent.com/73393296/140412338-f4a3cbdb-83a6-4eb2-8d5c-52f5358b96d2.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 15.2

**Comment by dokterkats** [comment]
Raivo had acces to iCloud in the iCloud settings

**Comment by tijme** [comment]
I know that some people are experiencing this issue. I'm not sure what causes this bug, but will look into it in the future.

**Comment by Enriquito** [comment]
I had the same problem and I had to enable "iCloud Drive" as it was disabled for me.

**Comment by tijme** [comment]
Closing this as it's being tracked in #64
