### ISSUE TITLE
Disroot.org svg can't be set but is on the repository

### ISSUE THREAD

**Issue by francescospelta** [raivo-otp/ios-application#81]
I wanted to add the disroot.org svg on the issuer-icons repo but it's already [there](https://github.com/raivo-otp/issuer-icons/tree/master/vectors/disroot.org). The problem is that I can't see it in the app.
![photo_2021-11-05_14-10-11](https://user-images.githubusercontent.com/54729294/140515648-dd65c06e-f108-49a5-af13-b38e9e31cc5b.jpg)

**Comment by tijme** [comment]
Hi @francescospelta,

I can see two disroot icons. Have you tapped the refresh button already? If not, can you do this and search for "disroot"?

**Comment by francescospelta** [comment]
I tried that before opening the issue but that didn't work back then.
Worked now, ty
