### ISSUE TITLE
How does the Raivo OTP export work?

### ISSUE THREAD

**Issue by Jayto1** [raivo-otp/ios-application#82]
What is included in the raivo exports? Do they work on other authenticators? Are they independant to your account so you could still manually import them?

New user here, so any info helps :)

**Comment by tijme** [comment]
**What is included in the Raivo exports?**
A JSON file and an HTML file. The HTML file also includes QR-codes. You can extract the ZIP-export using a ZIP tool that supports AES encryption. You must use your master password to extract the ZIP-file.

**Do they work on other authenticators?**
Yes, you can scan the QR-codes in the HTML file with any authenticator. 

**Are they independent to your account so you could still manually import them?**
Yes, you can import them in any authenticator and/or account.

**Comment by Jayto1** [comment]
> **What is included in the Raivo exports?** A JSON file and an HTML file. The HTML file also includes QR-codes. You can extract the ZIP-export using a ZIP tool that supports AES encryption. You must use your master password to extract the ZIP-file.
> 
> **Do they work on other authenticators?** Yes, you can scan the QR-codes in the HTML file with any authenticator.
> 
> **Are they independent to your account so you could still manually import them?** Yes, you can import them in any authenticator and/or account.

Thanks for taking the time to answer my questions, I really appreciate it. Do you plan on expanding to ecosystems other than iOS? Thanks.

**Comment by Jayto1** [comment]
@tijme any follow up?

**Comment by tijme** [comment]
The ecosystem is expanded to MacOS, but I'm not planning on further expanding it.

**Comment by Jayto1** [comment]
> The ecosystem is expanded to MacOS, but I'm not planning on further expanding it.

Sounds good, thanks for your help :)
