### ISSUE TITLE
Unable to scan QR codes while multitasking

### ISSUE THREAD

**Issue by AlexKraemer** [raivo-otp/ios-application#88]
**Describe the bug**
(1) While multitasking, both Split View and Slide Over, the "Scan a QR code" page will not show the viewfinder, nor will the application scan a QR code.

(2) Additionally, when using split view and on the "Scan a QR code" page, then making Raivo full screen, the viewfinder will return but will be distorted.  QR in this state can be scanned.

**To Reproduce**
Steps to reproduce the behavior: (1)
1. Use Raivo in Split View or Slide Over with any other app

Steps to reproduce the behavior: (2)
1. Use Raivo in Split View with another app
2. Make the Raivo app full screen

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: M1 iPad Pro 11"
 - OS: iPadOS 14.8.1
 
![IMG_1177](https://user-images.githubusercontent.com/9473033/143732242-80d7ba46-9542-4aa5-851d-4929668f801d.PNG)
![IMG_1175](https://user-images.githubusercontent.com/9473033/143732243-02f9acf3-fb74-43c7-b928-4538ee72a7d8.PNG)
![IMG_1176](https://user-images.githubusercontent.com/9473033/143732244-d55ba8de-c552-430f-a7b0-174a4f8075f8.PNG)

**Comment by tijme** [comment]
Thanks for the bug report @AlexKraemer !

**Comment by tijme** [comment]
Closing this as using the camera white multitasking is currently not supported in iOS. It will be supported in iOS 16, so I might implement this in the future.
