### ISSUE TITLE
Sync after first time denied

### ISSUE THREAD

**Issue by azoglufatih** [raivo-otp/ios-application#89]
1. Go to 'setting'
2. Click on 'Accoun or Provider'
3. See nothing is done

I wan't to sync it with my Cloud but there is still written ,,Synchrinisation is currently disabled". How can I enable it?

 - Device: IPhone 13 PRO MAX
 - OS: IOS 15
 - Version 15.1

I hope I am right here for my problem and hopefully you understand what I mean.

**Comment by tijme** [comment]
At the moment this is only possible at setup. Thus, to migrate to iCloud, you need to exports your OTP, sign out of Raivo, sign in using iCloud, and then import the exported OTP's.

**Comment by azoglufatih** [comment]
> At the moment this is only possible at setup. Thus, to migrate to iCloud, you need to exports your OTP, sign out of Raivo, sign in using iCloud, and then import the exported OTP's.

Where can I import the exported OTP‘s?

**Comment by ocompagne** [comment]
@azoglufatih As far as I can tell, right now there is no import feature. You need to open the zip backup, open the HTML file which shows all the QR codes, and add them to Raivo manually. A bit of a pain if you have many codes like me, but at least they're all on the same page and it's an acceptable method until an import feature is developed.
