### ISSUE TITLE
Incorrect master password when I tried to decrpyt my OTPs

### ISSUE THREAD

**Issue by NylaTheWolf** [raivo-otp/ios-application#90]
**Describe the bug**
I exported my data and saved it to iCloud, I tried to unzip it through The Unarchiver but it keeps saying my password is incorrect. I've written it down though. I can't tell if it's a bug or if I made a mistake when typing a master password or something.

**To Reproduce**
1. Go to Settings.
2. Click on "Export OTPs to Zip Archive"
3. Save the exported zip file to iCloud.
4. Use Keka or The Unarchiver.
5. Type in your master password when it prompts you
6. The app will say that the master password is wrong.

**Expected behavior**
To decrypt my OTPs when I give it the masterpassword.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iMac (21.5-inch, Late 2013)
 - OS: iOS 14; Mac Catalina
 - Version: iOS 14.8.1; Catalina 10.15.7

**Additional context**
It's possible that I made a mistake when typing in my master password or I wrote it down wrong.
Are my OTPs doomed though? Would I be forced to start all over again?

**Comment by bluto32** [comment]
This might be related to issue #59.
If you used any of these characters in your password, some Zip extractors may not accept it: £ € ¥ •

**Comment by NylaTheWolf** [comment]
> This might be related to issue #59. If you used any of these characters in your password, some Zip extractors may not accept it: £ € ¥ •

Yeah I saw that issue, but I didn't use any of those symbols in my password.

**Comment by tijme** [comment]
Could you try the default MacOS archive utility? If this doesn't work, and there are not weird characters in your ZIP, it might be that you entered an incorrect master password.

On last resort, you could try to unzip it on your iPhone (in the files app), which usually works.

**Comment by NylaTheWolf** [comment]
> Could you try the default MacOS archive utility? If this doesn't work, and there are not weird characters in your ZIP, it might be that you entered an incorrect master password.
> 
> On last resort, you could try to unzip it on your iPhone (in the files app), which usually works.

So...unzipping on my phone worked but uh...I realized that this whole time, I misspelt the password when I wrote it down, and I didn't realize it this entire time until I was typing it on my phone and realized that the word looked weird.

So I tried again with the correct spelling and it worked like a charm. So...that's embarrassing. Thank you for all your help though haha!
