### ISSUE TITLE
Change display name from “Raivo OTP” to “Raivo”

### ISSUE THREAD

**Issue by ylor** [raivo-otp/ios-application#91]
Before anything else, THANK YOU for this excellent app. 

**Is your feature request related to a problem? Please describe.**
This is pendantic but I would really like it if the display name for this app was “Raivo” instead of “Raivo OTP”

**Describe the solution you'd like**
Change the display name to “Raivo”

**Describe alternatives you've considered**
N/A.

**Additional context**
See screenshot below of how it currently appears and a rough mock-up of how it could appear.
![FF9D96D4-DA1D-45B5-919F-0F374653AB32](https://user-images.githubusercontent.com/2200609/145745036-d0b27f8d-f17b-4e4b-9efd-28e52ded3aac.jpeg)

**Comment by MrMuffinIsTaken** [comment]
Hard to do if the developer of the application is trying to indicated to people that they're downloading TOTP authenticator. A bypass for this is to use shortcuts.

**Comment by ylor** [comment]
Display name on springboard can differ from title at the App Store

**Comment by MrMuffinIsTaken** [comment]
@ylor I know, but people who don't now anything about 2FA might think that once they have Raivo installed and setup it some how automatically works and think that if it doesn't say TOTP next to it, they may just forget. And anther example of why this may not be such a great idea is, when "normal" people whom "normally" have over 50 to 70 application of their phone installed won't easily be able to search for their auth app when using the search function on their phone. There are many more examples of why having TOTP/OTP in the name is very hand. I get that it's possibly less ecstatically pleasing to some people. But it has many more advantages then one might think.

**Comment by ylor** [comment]
Can't imagine most "normal" people know what OTP means. Moreover anyone that goes through the trouble of setting up a TOTP/OTP code is unlikely to forget where they have it set up.

¯\_(ツ)_/¯

**Comment by MrMuffinIsTaken** [comment]
> Can't imagine most "normal" people know what OTP means. Moreover anyone that goes through the trouble of setting up a TOTP/OTP code is unlikely to forget where they have it set up.
> 

Fair Point. It was just an example of what happened once to someone it know.

**Comment by tijme** [comment]
Fixed in commit https://github.com/raivo-otp/ios-application/commit/76c4685281bdb3f7e9df98f365dce3422de044f2. Closing this issue as it will be pushed to public in a few weeks. It has to go through the verification and testing process first.
