### ISSUE TITLE
Categorisation

### ISSUE THREAD

**Issue by ncodee** [raivo-otp/ios-application#92]
**Is your feature request related to a problem? Please describe.**

Not really.

**Describe the solution you'd like**
Would be great if you could allow us to categorise our OTP codes on the main page. For example: Social, Business, Email etc.

**Describe alternatives you've considered**
An example of this feature can be found in the 2FAS app.

**Comment by meichthys** [comment]
Yes, this would be very helpful to keep business related codes separate. OTP Auth uses folders, but I'd be ok with anything that makes it clear which codes are personal and which are not.

**Comment by owenfiscus** [comment]
> Yes, this would be very helpful to keep business related codes separate. OTP Auth uses folders, but I'd be ok with anything that makes it clear which codes are personal and which are not.

I personally like the folder system, simple and intuitive.

**Comment by tijme** [comment]
Tracking in #9
