### ISSUE TITLE
Deleting app / signing out then reinstalling does not restore synced data

### ISSUE THREAD

**Issue by C4K3** [raivo-otp/ios-application#93]
Setting up the app to sync via iCloud, then deleting and reinstalling the app does not lead to a restoration of data.

* Set up app to use iCloud, add master password
* Add a TOTP token
* Says Status "Syncing up-to-date"
* Delete app
* Re-install app
* Set to use iCloud, use same master password as before
* It now says "It looks empty around here!" and the previously saved TOTP is not there anymore.

The same happens if I go to Settings -> Sign out of Raivo instead of deleting the app.

I would expect it to restore the existing synced data.

App version: 1.3.0 (build-53)
iOS version: 14.8.1

**Comment by tijme** [comment]
have you waited until the iCloud data became available. It could take a few seconds (10 to 20 seconds) before syncing is finished.

**Comment by tijme** [comment]
Furthermore, I cannot reproduce this issue. The data in iCloud is still there, as otherwise you wouldn't be able to sign in again afterwards (it checks the password you entered by decrypting an example record in iCloud).

**Comment by C4K3** [comment]
Yeah not sure, now I can't replicate it either.
