### ISSUE TITLE
The icon for IVPN is blank.

### ISSUE THREAD

**Issue by NylaTheWolf** [raivo-otp/ios-application#95]
**Describe the bug**
The vector for IVPN is blank. It's not even the icon that shows when you're searching and the icons are loading up or when you remove an icon from an account. It's just blank. I've tried closing the app, refreshing the icons a dozen times, and even shutting down my phone and powering it back up again, and it didn't work. This has only been happening this past week or so. I think I've seen the same thing happening to other icons, but IVPN has been constant and from it looks like right now no other icons have this issue. I think some of the blank icons were resolved by me turning my phone on and off a few minutes ago.

**To Reproduce**
1. Swipe on one of your accounts to edit it.
2. Click on your current icon.
3. Go to "Raivo's icon repository."
4. Search for IVPN or scroll down to IVPN.
5. See error.

**Expected behavior**
The IVPN vector shows up.

**Screenshots**
![](https://cdn.discordapp.com/attachments/895660579077906452/926571584708313108/D0B1E681-E9E1-47BC-8928-1726138D1067.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14
 - Version 8.1

**Additional context**
N/A

**Comment by tijme** [comment]
Thanks for the bug report @NylaTheWolf. Fixed in commit https://github.com/raivo-otp/issuer-icons/commit/cfaa0825becbb37d9149ba0aeda5c7eb69d4c9a6. Should work after a refresh!
