### ISSUE TITLE
QR Codes can't be read by other apps

### ISSUE THREAD

**Issue by ada-sk** [raivo-otp/ios-application#98]
**Describe the bug**
I'm switching off of ios and attempting to transfer my tokens to a new phone. When I scan QR codes from Raivo with other apps (aegis, freeotp, freeotp+), they cannot be read. These apps can scan from other sources without issue, just not the QR codes generated by Raivo.

**To Reproduce**
1. Show QR code for token in Raivo 
2. Scan code with Aegis, freeotp, or freeotp+

**Expected behavior**
Codes can be scanned in other OTP apps for easy transfer.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.2
 - Version: 1.3.0

**Comment by tijme** [comment]
Confirmed bug.

**Comment by tijme** [comment]
Will first be fixed in a TestFlight release. After testing this will be pushed to public release.

**Comment by tijme** [comment]
https://github.com/raivo-otp/ios-application/releases/tag/build-57
